/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorUsuario;
import Helper.EncrypPassw;
import Modelos.Usuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class ActualizarUser extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarUser
     */
    private UsuarioG usuarioG;
    private int idUsuario;
    private int id_cliente;
    //UsuarioG id = new UsuarioG();
    //int id_cliente = id.GetIdCliente();
    ControladorUsuario ctr = new ControladorUsuario();
     public void setIdCliente(int id) {
        this.id_cliente = id;
    }

    public ActualizarUser(UsuarioG usuarioG) {
        initComponents();
        this.usuarioG=usuarioG;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_rol = new javax.swing.JTextField();
        actualizarBtnUsu = new javax.swing.JPanel();
        txt_actualizarBtn = new javax.swing.JLabel();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Clave:");

        jLabel4.setText("Usuario:");

        jLabel5.setText("Rol:");

        actualizarBtnUsu.setBackground(new java.awt.Color(255, 255, 255));

        txt_actualizarBtn.setText("            Actualizar");
        txt_actualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_actualizarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_actualizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_actualizarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarBtnUsuLayout = new javax.swing.GroupLayout(actualizarBtnUsu);
        actualizarBtnUsu.setLayout(actualizarBtnUsuLayout);
        actualizarBtnUsuLayout.setHorizontalGroup(
            actualizarBtnUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        actualizarBtnUsuLayout.setVerticalGroup(
            actualizarBtnUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actualizarBtnUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actualizarBtnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_actualizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarBtnMouseEntered
        actualizarBtnUsu.setBackground(new Color(0, 153, 255));
        txt_actualizarBtn.setForeground(Color.white);
    }//GEN-LAST:event_txt_actualizarBtnMouseEntered

    private void txt_actualizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarBtnMouseExited
        actualizarBtnUsu.setBackground(Color.white);
        txt_actualizarBtn.setForeground(Color.black);
    }//GEN-LAST:event_txt_actualizarBtnMouseExited

    private void txt_actualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarBtnMouseClicked
        try {
            if (txt_nombre.getText().isEmpty() && txt_cedula.getText().isEmpty()
                    && txt_rol.getText().isEmpty() && txt_clave.getText().isEmpty() && txt_usuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "los campos estan vacios");

            } else {
                Usuario usuario = new Usuario();
                EncrypPassw encryp = new EncrypPassw();

                usuario.setNombre(txt_nombre.getText().trim());
                usuario.setCedula(txt_cedula.getText().trim());
                String pass = encryp.encriptarSHA256(txt_clave.getText().trim());
                usuario.setClave(pass);
                usuario.setRol(txt_rol.getText().trim());
                usuario.setUser(txt_usuario.getText().trim());

            if (ctr.actualizar(usuario,idUsuario)) {
                JOptionPane.showMessageDialog(null, "Actualizado extiosamente");
                usuarioG.CargarTablaUsuario();
                Limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar");

            }
            }
        } catch (Exception ex) {
            System.out.println("error" + ex);

        }
        

    }//GEN-LAST:event_txt_actualizarBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualizarBtnUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txt_actualizarBtn;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_rol;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    public void EnviarDatosClienteSeleccionada(int idUsuario) {
        try {
            Connection con = Conexionmy.Conectar();
            PreparedStatement pst = con.prepareStatement("select * from usuarios where id_usuario =?");
            //ResultSet rs = pst.executeQuery();
            pst.setInt(1, idUsuario);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_nombre.setText(rs.getString("nombre_usuario"));
                txt_cedula.setText(rs.getString("cedula"));
                txt_clave.setText(rs.getString("clave"));
                txt_rol.setText(rs.getString("rol"));
                txt_usuario.setText(rs.getString("userlogin"));

            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar cliente" + e);
        }
    }

    public void Limpiar() {
        txt_nombre.setText("");
        txt_cedula.setText("");
        txt_clave.setText("");
        txt_rol.setText("");
        txt_usuario.setText("");
    }
    
    public int PasaridUsuario(int idUsuario){
            return this.idUsuario = idUsuario;
    }
    
    
    public void ActualizarUser(int idUsuario) {
        
    
    
    }

}
