/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorCreditos;
import Modelos.Creditos;
import Ventanas.TblaClientesAtrasados;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */

public class ActualizarCredito extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarCredito
     */
    private TblaClientesAtrasados TblaClientes ;
    public String nombreAtrasado;
    ControladorCreditos ctrCred = new ControladorCreditos();
    
    Date fecha_reg = new Date();
    SimpleDateFormat formatear = new SimpleDateFormat("yyyy-MM-dd");
    private int id_tipo;
    public String cedulaAtrasado;
    // Datos del crédito (si tienes campos para mostrarlos)
    public String montoAtrasado;
    int Id_cliente;
    int id_Creditos;
    //cbx_interes.setSelectedItem(rs.getString("interes")); // 👈
    public String cuotasAtrasado;
    public double montoTotal;
    public double saldoPendienteAtrasado;

    public ActualizarCredito(TblaClientesAtrasados TblaClientes ) {
        initComponents();
        CargarTipoCredito();
        this.TblaClientes= TblaClientes;
        txt_fecharegRef.setText(formatear.format(fecha_reg));
        cbx_interes.addItem("10.0");
        cbx_interes.addItem("15.0");
        cbx_interes.addItem("20.0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cedulaAtrasado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1_tipoCred = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSpinner_cuotas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cbx_interes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_montoAtrasado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_saldoPendienteAtrasado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cuotasAtrasado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_newCuota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_totalrefinanciado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_nombreClienteAtrasado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_fecharegRef = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_fechaFinRef = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos del cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, -1));

        jLabel3.setText("Cedula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        txt_cedulaAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaAtrasadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cedulaAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 120, -1));

        jLabel4.setText("Modelo de pago: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel1.add(jComboBox1_tipoCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jLabel5.setText("Numero de cuotas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));
        jPanel1.add(jSpinner_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, -1));

        jLabel6.setText("Interes:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        jPanel1.add(cbx_interes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, -1));

        jLabel7.setText("Monto de credito:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 110, -1));
        jPanel1.add(txt_montoAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 190, -1));

        jLabel8.setText("Monto pendiente:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        txt_saldoPendienteAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saldoPendienteAtrasadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_saldoPendienteAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 190, -1));

        jLabel9.setText("Total de cuotas:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 90, -1));

        txt_cuotasAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuotasAtrasadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cuotasAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 190, -1));

        jLabel11.setText("Nueva Cuota:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        txt_newCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newCuotaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_newCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, -1));

        jLabel10.setText("Total:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, -1));

        txt_totalrefinanciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalrefinanciadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_totalrefinanciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 80, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel12.setText("   Calcular");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 70, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel13.setText("   Recuperar");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 80, 30));
        jPanel1.add(txt_nombreClienteAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, -1));

        jLabel14.setText("Fecha inicio:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 80, -1));
        jPanel1.add(txt_fecharegRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 110, -1));

        jLabel15.setText("fecha fin:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 70, -1));
        jPanel1.add(txt_fechaFinRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 110, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedulaAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaAtrasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaAtrasadoActionPerformed

    private void txt_saldoPendienteAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saldoPendienteAtrasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_saldoPendienteAtrasadoActionPerformed

    private void txt_cuotasAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuotasAtrasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cuotasAtrasadoActionPerformed

    private void txt_newCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newCuotaActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        calcularCredito();

    }//GEN-LAST:event_jLabel12MouseClicked

    private void txt_totalrefinanciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalrefinanciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalrefinanciadoActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        Creditos credito = new Creditos();
        if (!txt_nombreClienteAtrasado.getText().isEmpty() && !txt_cedulaAtrasado.getText().isEmpty()) {
            if (!jComboBox1_tipoCred.getSelectedItem().equals("Seleccione")) {
                if (!cbx_interes.getSelectedItem().equals("Seleccione")) {
                    if ((int) jSpinner_cuotas.getValue() != 0) {
                        credito.setIdcliente(Id_cliente);
                        credito.setMonto(Double.parseDouble(txt_saldoPendienteAtrasado.getText().trim().replace(",", ".")));
                        credito.setInteres(Double.parseDouble(cbx_interes.getSelectedItem().toString()));
                        credito.setCuotas(((int) jSpinner_cuotas.getValue()));
                        credito.setMontoTotal(Double.parseDouble(txt_totalrefinanciado.getText().trim().replace(",", ".")));
                        credito.setValorCuota(Double.parseDouble(txt_newCuota.getText().trim().replace(",", ".")));
                        credito.setSaldoPendiente(Double.parseDouble(txt_totalrefinanciado.getText().trim().replace(",", ".")));
                        try {
                            credito.setFechainicio(formatear.parse(txt_fecharegRef.getText().trim()));
                            credito.setFechafin(formatear.parse(txt_fechaFinRef.getText().trim()));
                        } catch (Exception ex) {
                            System.out.println("error en el parseo de las fecha" + ex);
                        }
                        //credito.setEstado("Pendiente");
                        //credito.setObservaciones(txt_observaciones.getText().trim());
                        obtenerIdTipo();
                        credito.setTipoCredito(id_tipo);

                        if (ctrCred.actualizarCreditoRef(credito, id_Creditos)) {
                            TblaClientes.cargarClientesConCuotasAtrasadas();
                            
                            JOptionPane.showMessageDialog(null, "Credito exitoso y se añadio como pendiente");
                            this.Limpiar();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Seleccione el numero de cuotas");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione el tipo interes");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de plazo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }
    
    }//GEN-LAST:event_jLabel13MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_interes;
    private javax.swing.JComboBox<String> jComboBox1_tipoCred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner_cuotas;
    private javax.swing.JTextField txt_cedulaAtrasado;
    private javax.swing.JTextField txt_cuotasAtrasado;
    private javax.swing.JTextField txt_fechaFinRef;
    private javax.swing.JTextField txt_fecharegRef;
    private javax.swing.JTextField txt_montoAtrasado;
    private javax.swing.JTextField txt_newCuota;
    private javax.swing.JTextField txt_nombreClienteAtrasado;
    private javax.swing.JTextField txt_saldoPendienteAtrasado;
    private javax.swing.JTextField txt_totalrefinanciado;
    // End of variables declaration//GEN-END:variables

    public void EnviarDatosClienteSeleccionados(int idCredito) {
        try {
            Connection con = Conexionmy.Conectar();
            String sql = """
            SELECT c.nombre, c.cedula, c.direccion, c.telefono, c.correo,
                   cr.id_credito,cr.monto, cr.interes, cr.cuotas, cr.monto_total,cr.valor_cuota, cr.saldo_pendiente,cr.estado, c.id_cliente
            FROM creditos cr
            INNER JOIN clientes c ON cr.id_cliente = c.id_cliente
            WHERE cr.id_credito = ?
        """;
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idCredito);
            ResultSet rs = pst.executeQuery();
            System.out.println("Ejecutando consulta con id_credito = " + idCredito);
            
            if (rs.next()) {
                // Datos del cliente

                
                //System.out.println(idCredito);
                txt_nombreClienteAtrasado.setText(rs.getString("nombre"));
                txt_cedulaAtrasado.setText(rs.getString("cedula"));

                // Datos del crédito (si tienes campos para mostrarlos)
                txt_montoAtrasado.setText(rs.getString("monto"));
                double interesBD = rs.getDouble("interes");
                String interesStr = String.valueOf(interesBD);
                cbx_interes.setSelectedItem(interesStr);
                txt_cuotasAtrasado.setText(rs.getString("cuotas"));
                //txt_montoTotal.setText(rs.getString("monto_total"));
                txt_saldoPendienteAtrasado.setText(rs.getString("saldo_pendiente"));
                //setearDatos();
                Id_cliente = rs.getInt("id_cliente");
                id_Creditos = idCredito;
                
            }

            con.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar datos del crédito y cliente: " + e);
        }
    }
    
    private void CargarTipoCredito() {
        Connection cn = Conexion.Conexionmy.Conectar();
        String sql = "select * from tipo_credito";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox1_tipoCred.removeAllItems();
            jComboBox1_tipoCred.addItem("Seleccione");
            while (rs.next()) {
                jComboBox1_tipoCred.addItem(rs.getString("tipo"));

            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar tipo de credito" + e);
        }

    }


private void obtenerIdTipo() {
        try {
            String sql = "select * from tipo_credito where tipo ='" + this.jComboBox1_tipoCred.getSelectedItem() + "'";
            Connection cn = Conexion.Conexionmy.Conectar();
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                id_tipo = rs.getInt("id_tipocredito");

            }

        } catch (SQLException e) {
            System.out.println("ERROR AL OBTENER ID DEL TIPO:" + e);
        }
    }
    
    
    public void calcularCredito() {
        try {
            // 1. Obtener datos
            double monto = Double.parseDouble(txt_saldoPendienteAtrasado.getText());
            Double interes = Double.parseDouble((String) cbx_interes.getSelectedItem());
            
            int cuotas = (Integer) jSpinner_cuotas.getValue();
            if(cuotas == 0){
                JOptionPane.showMessageDialog(null, "las cuotas no pueden ser 0");
                return ;
            }

            // 2. Calcular total con interés
            double totalConInteres = monto + (monto * interes / 100);

            // 3. Calcular valor de cada cuota
            double valorCuota = totalConInteres / cuotas;

            // 4. Asignar valores a los JTextField
            txt_totalrefinanciado.setText(String.format("%.2f", totalConInteres));
            txt_newCuota.setText(String.format("%.2f", valorCuota));
            calcularFechaFin();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Revisa los valores ingresados: " + e);
        }

    }
    
    
    
    public String calcularFechaFin() {
    DateTimeFormatter formatear = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String tipoCuota = (String) jComboBox1_tipoCred.getSelectedItem();
    int cuotas = (Integer) jSpinner_cuotas .getValue();
    
    LocalDate fechaInicio;
    
    try {
        fechaInicio = LocalDate.parse(txt_fecharegRef.getText().trim(), formatear);
        System.out.println(fechaInicio);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Formato de fecha de inicio inválido");
        return "";
    }

    LocalDate fechaFin = fechaInicio;

    // Calcular fecha de fin según tipo de cuota
    switch (tipoCuota) {
        case "Diario":
            fechaFin = fechaInicio.plusDays(cuotas);
            break;
        case "Semanal":
            fechaFin = fechaInicio.plusWeeks(cuotas);
            break;
        case "Mensual":
            fechaFin = fechaInicio.plusMonths(cuotas);
            break;
        default:
            System.out.println("Tipo de cuota no reconocido, usando fecha inicio como fecha fin.");
    }

    // Mostrar fecha fin en el txt correspondiente
    String fechaFinStr = fechaFin.format(formatear);
    txt_fechaFinRef.setText(fechaFinStr);
        System.out.println(txt_fechaFinRef);

    return fechaFinStr;
}
public void Limpiar(){
    txt_nombreClienteAtrasado.setText("");
    txt_cedulaAtrasado.setText("");
    txt_montoAtrasado.setText("");
    txt_cuotasAtrasado.setText("");
    txt_saldoPendienteAtrasado.setText("");
    txt_newCuota.setText("");
    txt_totalrefinanciado.setText("");
    txt_fechaFinRef.setText("");
    txt_fecharegRef.setText("");
    jSpinner_cuotas.setValue(0);
    jComboBox1_tipoCred.setSelectedItem("Seleccione");
    cbx_interes.setSelectedItem("Seleccione");
}

}
