/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorCliente;
import Controladores.ControladorCreditos;
import Modelos.Creditos;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class AgregarCredito extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCredito
     */
    private CreditosG creditosG;
    Date fecha_reg = new Date();
    SimpleDateFormat formatear = new SimpleDateFormat("yyyy-MM-dd");
    private int id_cliente;
    ControladorCreditos ctr = new ControladorCreditos();
    private int id_tipo;

    public AgregarCredito(CreditosG creditosG) {
        initComponents();
        CargarTipoCredito();
        this.creditosG=creditosG;
//        txt_cedulaCliente.setEditable(false);
//        txt_nombreCliente.setEditable(false);
        txt_fechareg.setText(formatear.format(fecha_reg));
        jComboBox_interes.addItem("10");
        jComboBox_interes.addItem("15");
        jComboBox_interes.addItem("20");

    }

    public String GetTxtbuscarCedula() {
        return txt_buscarCedula.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ingreseCedulaBtn = new javax.swing.JPanel();
        txt_ingreseCedula = new javax.swing.JLabel();
        txt_buscarCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_cedulaCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_tipoC = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_interes = new javax.swing.JComboBox<>();
        jSpinner_cuotas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cuotaF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_totalconI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_fechareg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_fechafin = new javax.swing.JTextField();
        agregarCreditoBtn = new javax.swing.JPanel();
        txt_agregarCredito = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_observaciones = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JPanel();
        txt_calcular = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setPreferredSize(new java.awt.Dimension(770, 210));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(761, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreseCedulaBtn.setBackground(new java.awt.Color(204, 204, 204));

        txt_ingreseCedula.setText("  Ingrese cedula");
        txt_ingreseCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ingreseCedulaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ingreseCedulaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ingreseCedulaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingreseCedulaBtnLayout = new javax.swing.GroupLayout(ingreseCedulaBtn);
        ingreseCedulaBtn.setLayout(ingreseCedulaBtnLayout);
        ingreseCedulaBtnLayout.setHorizontalGroup(
            ingreseCedulaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ingreseCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ingreseCedulaBtnLayout.setVerticalGroup(
            ingreseCedulaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ingreseCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jPanel1.add(ingreseCedulaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, -1));
        jPanel1.add(txt_buscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 7, 126, -1));

        jLabel2.setText("           Datos del cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 35, 171, -1));

        txt_nombreCliente.setEditable(false);
        jPanel1.add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, 115, -1));

        txt_cedulaCliente.setEditable(false);
        jPanel1.add(txt_cedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 57, 112, -1));

        jLabel3.setText("Modelo de pago:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        jComboBox_tipoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox_tipoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 116, -1));

        jLabel4.setText("Numero de cuotas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 111, -1));

        jLabel5.setText("Interes:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 72, -1));

        jComboBox_interes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox_interes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_interesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_interes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 116, -1));
        jPanel1.add(jSpinner_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, -1));

        jLabel6.setText("Monto credito:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 80, -1));
        jPanel1.add(txt_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 230, -1));

        jLabel7.setText("Cuota:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 40, -1));

        txt_cuotaF.setEditable(false);
        jPanel1.add(txt_cuotaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 55, -1));

        jLabel8.setText("Monto total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        txt_totalconI.setEditable(false);
        jPanel1.add(txt_totalconI, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 92, -1));

        jLabel9.setText("Fecha registro:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 86, -1));

        txt_fechareg.setEditable(false);
        txt_fechareg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecharegActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fechareg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 90, -1));

        jLabel10.setText("Hasta:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        txt_fechafin.setEditable(false);
        txt_fechafin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechafinActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 83, -1));

        agregarCreditoBtn.setBackground(new java.awt.Color(255, 255, 255));
        agregarCreditoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_agregarCredito.setText("   Agregar credito");
        txt_agregarCredito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_agregarCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_agregarCreditoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_agregarCreditoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_agregarCreditoMouseExited(evt);
            }
        });
        agregarCreditoBtn.add(txt_agregarCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(agregarCreditoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 101, 30));

        jLabel12.setText("Obesrvacion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));
        jPanel1.add(txt_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 230, -1));

        calcularBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_calcular.setText("          Calcular");
        txt_calcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_calcularMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_calcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_calcularMouseExited(evt);
            }
        });

        javax.swing.GroupLayout calcularBtnLayout = new javax.swing.GroupLayout(calcularBtn);
        calcularBtn.setLayout(calcularBtnLayout);
        calcularBtnLayout.setHorizontalGroup(
            calcularBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        calcularBtnLayout.setVerticalGroup(
            calcularBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(calcularBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ingreseCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingreseCedulaMouseClicked
        buscarUsuarioPorCedula(txt_buscarCedula.getText());
        txt_buscarCedula.setText("");
    }//GEN-LAST:event_txt_ingreseCedulaMouseClicked

    private void txt_fechafinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechafinActionPerformed

    }//GEN-LAST:event_txt_fechafinActionPerformed

    private void txt_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_calcularMouseClicked
        calcularCredito();
        calcularFechaFin();


    }//GEN-LAST:event_txt_calcularMouseClicked

    private void txt_agregarCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarCreditoMouseClicked
        Creditos credito = new Creditos();
        if(!txt_nombreCliente.getText().isEmpty() && !txt_cedulaCliente.getText().isEmpty()){
            if(!jComboBox_tipoC.getSelectedItem().equals("Seleccione")){
                if(!jComboBox_interes.getSelectedItem().equals("Seleccione")){
                    if((int)jSpinner_cuotas.getValue()!=0){
                        if(!txt_buscarCedula.getText().isEmpty() || !txt_nombreCliente.getText().isEmpty()){
                            credito.setIdcliente(id_cliente);
                            credito.setMonto(Double.parseDouble(txt_monto.getText().trim().replace(",", ".")));
                            credito.setInteres(Integer.parseInt(jComboBox_interes.getSelectedItem().toString()));
                            credito.setCuotas(((int) jSpinner_cuotas.getValue()));
                            credito.setMontoTotal(Double.parseDouble(txt_totalconI.getText().trim().replace(",", ".")) );
                            credito.setValorCuota(Double.parseDouble(txt_cuotaF.getText().trim().replace(",", ".")));
                            credito.setSaldoPendiente(Double.parseDouble(txt_totalconI.getText().trim().replace(",", ".")));
                            try{
                            credito.setFechainicio(formatear.parse(txt_fechareg.getText().trim()));
                            credito.setFechafin(formatear.parse(txt_fechafin.getText().trim()));
                            }catch(Exception ex){
                                System.out.println("error en el parseo de las fecha" + ex);
                            }
                            credito.setEstado("Pendiente");
                            credito.setObservaciones(txt_observaciones.getText().trim());
                            obtenerIdTipo();
                            credito.setTipoCredito(id_tipo);

                            if(ctr.guardar(credito)){
                                creditosG.CargarTablaCredito();
                                JOptionPane.showMessageDialog(null, "Credito exitoso y se añadio como pendiente");
                                this.Limpiar();
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Ingrese numero de cedula");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Seleccione el numero de cuotas");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Seleccione el tipo interes");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Seleccione el tipo de plazo");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }
    }//GEN-LAST:event_txt_agregarCreditoMouseClicked

    private void txt_fecharegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecharegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecharegActionPerformed

    private void txt_agregarCreditoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarCreditoMouseEntered
        agregarCreditoBtn.setBackground(new Color(0, 153, 255));
        txt_agregarCredito.setForeground(Color.white);
    }//GEN-LAST:event_txt_agregarCreditoMouseEntered

    private void txt_agregarCreditoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarCreditoMouseExited
        agregarCreditoBtn.setBackground(Color.white);
        txt_agregarCredito.setForeground(Color.black);
    }//GEN-LAST:event_txt_agregarCreditoMouseExited

    private void txt_calcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_calcularMouseEntered
        calcularBtn.setBackground(new Color(0, 153, 255));
        txt_calcular.setForeground(Color.white);
    }//GEN-LAST:event_txt_calcularMouseEntered

    private void txt_calcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_calcularMouseExited
        calcularBtn.setBackground(Color.white);
        txt_calcular.setForeground(Color.black);
    }//GEN-LAST:event_txt_calcularMouseExited

    private void txt_ingreseCedulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingreseCedulaMouseEntered
        ingreseCedulaBtn.setBackground(new Color(0, 153, 255));
        txt_ingreseCedula.setForeground(Color.white);
    }//GEN-LAST:event_txt_ingreseCedulaMouseEntered

    private void txt_ingreseCedulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingreseCedulaMouseExited
        ingreseCedulaBtn.setBackground(Color.white);
        txt_ingreseCedula.setForeground(Color.black);
    }//GEN-LAST:event_txt_ingreseCedulaMouseExited

    private void jComboBox_interesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_interesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_interesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarCreditoBtn;
    private javax.swing.JPanel calcularBtn;
    private javax.swing.JPanel ingreseCedulaBtn;
    private javax.swing.JComboBox<String> jComboBox_interes;
    private javax.swing.JComboBox<String> jComboBox_tipoC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_cuotas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel txt_agregarCredito;
    private javax.swing.JTextField txt_buscarCedula;
    private javax.swing.JLabel txt_calcular;
    private javax.swing.JTextField txt_cedulaCliente;
    private javax.swing.JTextField txt_cuotaF;
    private javax.swing.JTextField txt_fechafin;
    private javax.swing.JTextField txt_fechareg;
    private javax.swing.JLabel txt_ingreseCedula;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_observaciones;
    private javax.swing.JTextField txt_totalconI;
    // End of variables declaration//GEN-END:variables

    private void CargarTipoCredito() {
        Connection cn = Conexion.Conexionmy.Conectar();
        String sql = "select * from tipo_credito";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_tipoC.removeAllItems();
            jComboBox_tipoC.addItem("Seleccione");
            while (rs.next()) {
                jComboBox_tipoC.addItem(rs.getString("tipo"));

            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar tipo de credito" + e);
        }

    }

    private void obtenerIdTipo() {
        try {
            String sql = "select * from tipo_credito where tipo ='" + this.jComboBox_tipoC.getSelectedItem() + "'";
            Connection cn = Conexion.Conexionmy.Conectar();
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                id_tipo = rs.getInt("id_tipocredito");

            }

        } catch (SQLException e) {
            System.out.println("ERROR AL OBTENER ID DEL TIPO:" + e);
        }
    }

    public void buscarUsuarioPorCedula(String cedula) {
        Connection con = Conexionmy.Conectar();
        String BuscarUser = cedula.trim();

        if (BuscarUser.isEmpty()) {
            return; // No hacer búsqueda si está vacío
        }

        String sql = "SELECT * FROM clientes WHERE cedula LIKE ?;";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, "%" + BuscarUser + "%"); // Busca coincidencias parciales en la cédula

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                id_cliente = rs.getInt("id_cliente");
                txt_nombreCliente.setText(rs.getString("nombre"));
                txt_cedulaCliente.setText(rs.getString("cedula"));
            } else {
                System.out.println("⚠ No se encontró cliente con cédula: " + BuscarUser);
            }

            con.close();
        } catch (SQLException e) {
            System.out.println("Error al buscar Cliente: " + e);
        }

    }

    public void calcularCredito() {
        try {
            // 1. Obtener datos
            double monto = Double.parseDouble(txt_monto.getText());
            int interes = Integer.parseInt((String) jComboBox_interes.getSelectedItem());
            int cuotas = (Integer) jSpinner_cuotas.getValue();

            // 2. Calcular total con interés
            double totalConInteres = monto + (monto * interes / 100);

            // 3. Calcular valor de cada cuota
            double valorCuota = totalConInteres / cuotas;

            // 4. Asignar valores a los JTextField
            txt_totalconI.setText(String.format("%.2f", totalConInteres));
            txt_cuotaF.setText(String.format("%.2f", valorCuota));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Revisa los valores ingresados: " + e);
        }

    }

    public String calcularFechaFin() {
    DateTimeFormatter formatear = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    String tipoCuota = (String) jComboBox_tipoC.getSelectedItem();
    int cuotas = (Integer) jSpinner_cuotas.getValue();
    
    LocalDate fechaInicio;
    try {
        fechaInicio = LocalDate.parse(txt_fechareg.getText().trim(), formatear);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Formato de fecha de inicio inválido");
        return "";
    }

    LocalDate fechaFin = fechaInicio;

    // Calcular fecha de fin según tipo de cuota
    switch (tipoCuota) {
        case "Diario":
            fechaFin = fechaInicio.plusDays(cuotas);
            break;
        case "Semanal":
            fechaFin = fechaInicio.plusWeeks(cuotas);
            break;
        case "Mensual":
            fechaFin = fechaInicio.plusMonths(cuotas);
            break;
        default:
            System.out.println("Tipo de cuota no reconocido, usando fecha inicio como fecha fin.");
    }

    // Mostrar fecha fin en el txt correspondiente
    String fechaFinStr = fechaFin.format(formatear);
    txt_fechafin.setText(fechaFinStr);

    return fechaFinStr;
}

    
public void Limpiar(){
    txt_cedulaCliente.setText("");
    txt_buscarCedula.setText("");
    txt_cuotaF.setText("");
    txt_fechafin.setText("");
    txt_fechareg.setText("");
    txt_monto.setText("");
    txt_nombreCliente.setText("");
    txt_observaciones.setText("");
    txt_totalconI.setText("");
    jSpinner_cuotas.setValue(0);
    jComboBox_tipoC.setSelectedItem("Seleccione");
    jComboBox_interes.setSelectedItem("Seleccione");
}
}
