/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorCliente;
import Controladores.ControladorUsuario;
import Helper.EncrypPassw;
import Modelos.Cliente;
import Modelos.Usuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class AgregarClient extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarUser
     */
    private ClientesG usuarioG;
    private int idUsuario;
    private int id_cliente;
    //UsuarioG id = new UsuarioG();
    //int id_cliente = id.GetIdCliente();
    ControladorUsuario ctr = new ControladorUsuario();

    public void setIdCliente(int id) {
        this.id_cliente = id;
    }

    public AgregarClient(ClientesG usuarioG) {
        initComponents();
        this.usuarioG = usuarioG;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        actualizarBtnUsu = new javax.swing.JPanel();
        txt_actualizarBtn = new javax.swing.JLabel();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Direccion:");

        jLabel3.setText("Cedula:");

        jLabel4.setText("Correo:");

        jLabel5.setText("Telefono:");

        actualizarBtnUsu.setBackground(new java.awt.Color(255, 255, 255));

        txt_actualizarBtn.setText("         Añadir Cliente");
        txt_actualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_actualizarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_actualizarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_actualizarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarBtnUsuLayout = new javax.swing.GroupLayout(actualizarBtnUsu);
        actualizarBtnUsu.setLayout(actualizarBtnUsuLayout);
        actualizarBtnUsuLayout.setHorizontalGroup(
            actualizarBtnUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        actualizarBtnUsuLayout.setVerticalGroup(
            actualizarBtnUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actualizarBtnUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(actualizarBtnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_actualizarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarBtnMouseEntered
        actualizarBtnUsu.setBackground(new Color(0, 153, 255));
        txt_actualizarBtn.setForeground(Color.white);
    }//GEN-LAST:event_txt_actualizarBtnMouseEntered

    private void txt_actualizarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarBtnMouseExited
        actualizarBtnUsu.setBackground(Color.white);
        txt_actualizarBtn.setForeground(Color.black);
    }//GEN-LAST:event_txt_actualizarBtnMouseExited

    private void txt_actualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarBtnMouseClicked
        Cliente cliente = new Cliente();
        ControladorCliente controladorCliente = new ControladorCliente();
        EncrypPassw encryp = new EncrypPassw();

        if (!txt_nombre.getText().isEmpty() && !txt_direccion.getText().isEmpty() && !txt_correo.getText().isEmpty() && !txt_cedula.getText().isEmpty() && !txt_telefono.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "guardado");

            if (!controladorCliente.clienteExiste(txt_cedula.getText().trim())) {
                
                    cliente.setNombre(txt_nombre.getText().trim());
                    cliente.setCedula(txt_cedula.getText().trim());
                    cliente.setCorreo(txt_correo.getText().trim());
                    cliente.setDireccion(txt_direccion.getText().trim());
                    cliente.setTelefono(txt_telefono.getText().trim());
                    if (controladorCliente.guardar(cliente)) {
                        txt_nombre.setBackground(Color.GREEN);
                        txt_direccion.setBackground(Color.GREEN);
                        txt_correo.setBackground(Color.GREEN);
                        txt_cedula.setBackground(Color.GREEN);
                        txt_telefono.setBackground(Color.GREEN);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                        usuarioG.CargarTablaCliente();
                        txt_nombre.setBackground(Color.white);
                        txt_direccion.setBackground(Color.white);
                        txt_cedula.setBackground(Color.white);
                        txt_correo.setBackground(Color.white);
                        txt_telefono.setBackground(Color.white);

                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");

                    }
                

            } else {
                txt_nombre.setBackground(Color.yellow);
                txt_direccion.setBackground(Color.yellow);
                txt_cedula.setBackground(Color.yellow);
                txt_correo.setBackground(Color.yellow);
                txt_telefono.setBackground(Color.yellow);
                JOptionPane.showMessageDialog(null, "El Usuario ya existe");
                txt_nombre.setBackground(Color.white);
                txt_direccion.setBackground(Color.white);
                txt_cedula.setBackground(Color.white);
                txt_correo.setBackground(Color.white);
                txt_telefono.setBackground(Color.white);

            }

        } else {
            txt_nombre.setBackground(Color.red);
            txt_direccion.setBackground(Color.red);
            txt_cedula.setBackground(Color.red);
            txt_correo.setBackground(Color.red);
            txt_telefono.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "complete campos obligatorios");
            txt_nombre.setBackground(Color.white);
            txt_direccion.setBackground(Color.white);
            txt_cedula.setBackground(Color.white);
            txt_correo.setBackground(Color.white);
            txt_telefono.setBackground(Color.white);
        }

        //llamamos al metodo limpiar 
        Limpiar();


    }//GEN-LAST:event_txt_actualizarBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualizarBtnUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txt_actualizarBtn;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    public int PasaridUsuario(int idUsuario) {
        return this.idUsuario = idUsuario;
    }
     public void Limpiar() {
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_cedula.setText("");
        txt_telefono.setText("");
        txt_correo.setText("");
    }
}
