/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorCliente;
import Controladores.ControladorUsuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class ClientesG extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioG
     */
    private int id_cliente;
    ControladorCliente client = new ControladorCliente();
    ActualizarClient act = new ActualizarClient(this);
    AgregarClient addClient= new AgregarClient(this);

    public ClientesG() {
        initComponents();
        CargarTablaCliente();

    }

    public int GetIdCliente() {
        return id_cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarUsuarioBtn = new javax.swing.JPanel();
        txt_buscarusuario = new javax.swing.JLabel();
        txt_buscarName = new javax.swing.JTextField();
        buscarCBtn = new javax.swing.JPanel();
        txt_buscarcedula = new javax.swing.JLabel();
        txt_buscarCedula = new javax.swing.JTextField();
        paneltabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cliente = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        actualizarBtnUsuario = new javax.swing.JPanel();
        txt_Actualiz = new javax.swing.JLabel();
        actualizarTablaBtn = new javax.swing.JPanel();
        txt_actualizartblaBtn = new javax.swing.JLabel();
        ContenAct = new javax.swing.JPanel();
        addUserBtn = new javax.swing.JPanel();
        txt_addUser = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(231, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarUsuarioBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_buscarusuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_buscarusuario.setText("   Buscar Cliente:");
        txt_buscarusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_buscarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarUsuarioBtnLayout = new javax.swing.GroupLayout(buscarUsuarioBtn);
        buscarUsuarioBtn.setLayout(buscarUsuarioBtnLayout);
        buscarUsuarioBtnLayout.setHorizontalGroup(
            buscarUsuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        buscarUsuarioBtnLayout.setVerticalGroup(
            buscarUsuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(buscarUsuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        txt_buscarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_buscarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, 30));

        buscarCBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_buscarcedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_buscarcedula.setText("  Buscar nombre:");
        txt_buscarcedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_buscarcedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarcedulaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_buscarcedulaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_buscarcedulaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarCBtnLayout = new javax.swing.GroupLayout(buscarCBtn);
        buscarCBtn.setLayout(buscarCBtnLayout);
        buscarCBtnLayout.setHorizontalGroup(
            buscarCBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarcedula, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        buscarCBtnLayout.setVerticalGroup(
            buscarCBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarcedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(buscarCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        txt_buscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_buscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, 30));

        paneltabla.setBackground(new java.awt.Color(153, 153, 153));
        paneltabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_cliente.setBackground(new java.awt.Color(246, 246, 246));
        jTable_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_cliente);

        paneltabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 190));

        jPanel1.add(paneltabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1010, 190));

        jPanel5.setBackground(new java.awt.Color(231, 250, 250));

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setText("                    GESTION DE Clientes");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 480, 40));

        actualizarBtnUsuario.setBackground(new java.awt.Color(255, 255, 255));

        txt_Actualiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_Actualiz.setText("     Actualizar clientes");
        txt_Actualiz.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_Actualiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ActualizMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ActualizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ActualizMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarBtnUsuarioLayout = new javax.swing.GroupLayout(actualizarBtnUsuario);
        actualizarBtnUsuario.setLayout(actualizarBtnUsuarioLayout);
        actualizarBtnUsuarioLayout.setHorizontalGroup(
            actualizarBtnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Actualiz, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        actualizarBtnUsuarioLayout.setVerticalGroup(
            actualizarBtnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Actualiz, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(actualizarBtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 140, 30));

        actualizarTablaBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_actualizartblaBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_actualizartblaBtn.setText("        Actualizar tabla");
        txt_actualizartblaBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_actualizartblaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_actualizartblaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_actualizartblaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_actualizartblaBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarTablaBtnLayout = new javax.swing.GroupLayout(actualizarTablaBtn);
        actualizarTablaBtn.setLayout(actualizarTablaBtnLayout);
        actualizarTablaBtnLayout.setHorizontalGroup(
            actualizarTablaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizartblaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        actualizarTablaBtnLayout.setVerticalGroup(
            actualizarTablaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizartblaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(actualizarTablaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 140, 30));

        ContenAct.setBackground(new java.awt.Color(231, 250, 250));

        javax.swing.GroupLayout ContenActLayout = new javax.swing.GroupLayout(ContenAct);
        ContenAct.setLayout(ContenActLayout);
        ContenActLayout.setHorizontalGroup(
            ContenActLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        ContenActLayout.setVerticalGroup(
            ContenActLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.add(ContenAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 376, 560, 180));

        addUserBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_addUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_addUser.setText("      Agregar Cliente");
        txt_addUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txt_addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_addUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_addUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout addUserBtnLayout = new javax.swing.GroupLayout(addUserBtn);
        addUserBtn.setLayout(addUserBtnLayout);
        addUserBtnLayout.setHorizontalGroup(
            addUserBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_addUser, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        addUserBtnLayout.setVerticalGroup(
            addUserBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_addUser, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarNameActionPerformed

    private void txt_buscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarCedulaActionPerformed

    private void txt_buscarusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseEntered
        buscarUsuarioBtn.setBackground(new Color(0, 153, 255));
        txt_buscarusuario.setForeground(Color.white);
    }//GEN-LAST:event_txt_buscarusuarioMouseEntered

    private void txt_buscarusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseExited
        buscarUsuarioBtn.setBackground(Color.white);
        txt_buscarusuario.setForeground(Color.black);
    }//GEN-LAST:event_txt_buscarusuarioMouseExited

    private void txt_buscarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseClicked
        String isOk = client.buscarUsuarioPorCedula(GetTxtbuscarCedula());
        if(isOk.equals("404"))JOptionPane.showMessageDialog(null,"no existe cliente o cedula mal ingresada");
        
        txt_buscarCedula.setText("");
    }//GEN-LAST:event_txt_buscarusuarioMouseClicked

    private void txt_buscarcedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcedulaMouseClicked
        client.buscarUsuarioPorName(GetTxtbuscarName());
        txt_buscarName.setText("");
    }//GEN-LAST:event_txt_buscarcedulaMouseClicked

    private void txt_actualizartblaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizartblaBtnMouseClicked
        CargarTablaCliente();
    }//GEN-LAST:event_txt_actualizartblaBtnMouseClicked

    private void txt_ActualizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ActualizMouseClicked
        
        ShowPanel(act);
    }//GEN-LAST:event_txt_ActualizMouseClicked

    private void txt_buscarcedulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcedulaMouseEntered
        buscarCBtn.setBackground(new Color(0, 153, 255));
        txt_buscarcedula.setForeground(Color.white);
    }//GEN-LAST:event_txt_buscarcedulaMouseEntered

    private void txt_ActualizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ActualizMouseEntered
        actualizarBtnUsuario.setBackground(new Color(0, 153, 255));
        txt_Actualiz.setForeground(Color.white);
    }//GEN-LAST:event_txt_ActualizMouseEntered

    private void txt_actualizartblaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizartblaBtnMouseEntered
        actualizarTablaBtn.setBackground(new Color(0, 153, 255));
        actualizarTablaBtn.setForeground(Color.white);
    }//GEN-LAST:event_txt_actualizartblaBtnMouseEntered

    private void txt_buscarcedulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcedulaMouseExited
         buscarCBtn.setBackground(Color.white);
        txt_buscarcedula.setForeground(Color.black);
    }//GEN-LAST:event_txt_buscarcedulaMouseExited

    private void txt_ActualizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ActualizMouseExited
        actualizarBtnUsuario.setBackground(Color.white);
        txt_Actualiz.setForeground(Color.black);
    }//GEN-LAST:event_txt_ActualizMouseExited

    private void txt_actualizartblaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizartblaBtnMouseExited
        actualizarTablaBtn.setBackground(Color.white);
        txt_actualizartblaBtn.setForeground(Color.black);
    }//GEN-LAST:event_txt_actualizartblaBtnMouseExited

    private void txt_addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addUserMouseClicked
        ShowPanel(addClient);
    }//GEN-LAST:event_txt_addUserMouseClicked

    private void txt_addUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addUserMouseEntered
        addUserBtn.setBackground(new Color(0, 153, 255));
        txt_addUser.setForeground(Color.white);
    }//GEN-LAST:event_txt_addUserMouseEntered

    private void txt_addUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addUserMouseExited
        addUserBtn.setBackground(Color.white);
        txt_addUser.setForeground(Color.black);
    }//GEN-LAST:event_txt_addUserMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenAct;
    private javax.swing.JPanel actualizarBtnUsuario;
    private javax.swing.JPanel actualizarTablaBtn;
    private javax.swing.JPanel addUserBtn;
    private javax.swing.JPanel buscarCBtn;
    private javax.swing.JPanel buscarUsuarioBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_cliente;
    private javax.swing.JPanel paneltabla;
    private javax.swing.JLabel txt_Actualiz;
    private javax.swing.JLabel txt_actualizartblaBtn;
    private javax.swing.JLabel txt_addUser;
    private javax.swing.JTextField txt_buscarCedula;
    private javax.swing.JTextField txt_buscarName;
    private javax.swing.JLabel txt_buscarcedula;
    private javax.swing.JLabel txt_buscarusuario;
    // End of variables declaration//GEN-END:variables

    public String GetTxtbuscarName() {
        return txt_buscarName.getText();
    }

    public String GetTxtbuscarCedula() {
        return txt_buscarCedula.getText();
    }

    private void ShowPanel(JPanel p) {
        p.setSize(600, 180);
        p.setLocation(0, 0);
        ContenAct.removeAll();
        ContenAct.setLayout(new BorderLayout());
        ContenAct.add(p, BorderLayout.CENTER);
        ContenAct.revalidate();
        ContenAct.repaint();

    }

//Cargar la tabla de usuarios registrados
    public void CargarTablaCliente() {
        Connection con = Conexionmy.Conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT * FROM clientes;";
        Statement st;

        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            model.addColumn("N°");
            model.addColumn("Nombre");
            model.addColumn("cedula");
            model.addColumn("Telefono");
            model.addColumn("Direccion");
            model.addColumn("Correo");

            while (rs.next()) {

                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);

                }

                model.addRow(fila);
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar tabla cliente" + e);
        }
        jTable_cliente.setModel(model);
        

        jTable_cliente.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_cliente.rowAtPoint(e.getPoint());
                int columna_point = 0;
                int selectedRow = jTable_cliente.getSelectedRow();

                if (fila_point >= 0) {
                    id_cliente = (int) jTable_cliente.getValueAt(selectedRow, 0);
                    act.PasaridCliente(id_cliente);
                    act.EnviarDatosClienteSeleccionada(id_cliente);
                    
                    //EnviarDatosClienteSeleccionada(idCliente);

                }
            }
        });
    }

}
