/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Bryan
 */
public class ClientesEnRiesgo extends javax.swing.JPanel {

    /**
     * Creates new form ClientesEnRiesgo
     */
    public ClientesEnRiesgo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tablaMora = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("CLIENTES EN RIESGO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 40));

        javax.swing.GroupLayout tablaMoraLayout = new javax.swing.GroupLayout(tablaMora);
        tablaMora.setLayout(tablaMoraLayout);
        tablaMoraLayout.setHorizontalGroup(
            tablaMoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        tablaMoraLayout.setVerticalGroup(
            tablaMoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(tablaMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 750, 430));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tablaMora;
    // End of variables declaration//GEN-END:variables



private void ShowPanel(JPanel p) {
        p.setSize(600, 180);
        p.setLocation(0, 0);
        tablaMora.removeAll();
        tablaMora.setLayout(new BorderLayout());
        tablaMora.add(p, BorderLayout.CENTER);
        tablaMora.revalidate();
        tablaMora.repaint();

    }


}
