/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorCreditos;
import static Ventanas.ClientesG.jTable_cliente;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class CreditosG extends javax.swing.JPanel {

    /**
     * Creates new form CreditosG
     */
    ControladorCreditos ctrCr = new ControladorCreditos();
    AgregarCredito credit = new AgregarCredito(this);
    RealizarPagoCredito pagoCredit = new RealizarPagoCredito(this);
    private int id_credito;
    public CreditosG() {
        initComponents();
        CargarTablaCredito();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_creditos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        transacc = new javax.swing.JPanel();
        AgregarClientBnt = new javax.swing.JPanel();
        txt_agregarcliente = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JPanel();
        BtnBuscarCredito = new javax.swing.JLabel();
        txt_buscarCredit = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_creditos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_creditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_creditos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 770, 230));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("         Gestion de creditos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 361, 37));

        transacc.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout transaccLayout = new javax.swing.GroupLayout(transacc);
        transacc.setLayout(transaccLayout);
        transaccLayout.setHorizontalGroup(
            transaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        transaccLayout.setVerticalGroup(
            transaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(transacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 770, 210));

        txt_agregarcliente.setText("     Agregar Credito");
        txt_agregarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_agregarclienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_agregarclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_agregarclienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AgregarClientBntLayout = new javax.swing.GroupLayout(AgregarClientBnt);
        AgregarClientBnt.setLayout(AgregarClientBntLayout);
        AgregarClientBntLayout.setHorizontalGroup(
            AgregarClientBntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_agregarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        AgregarClientBntLayout.setVerticalGroup(
            AgregarClientBntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_agregarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(AgregarClientBnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 339, 120, 30));

        jLabel4.setText("Ver clientes atrasados");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 339, -1, 30));

        jLabel5.setText("    Registrar Pago");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 339, -1, 30));

        BtnBuscarCredito.setText("        Buscar");
        BtnBuscarCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarCreditoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBuscarCreditoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBuscarCreditoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnBuscarLayout = new javax.swing.GroupLayout(BtnBuscar);
        BtnBuscar.setLayout(BtnBuscarLayout);
        BtnBuscarLayout.setHorizontalGroup(
            BtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnBuscarLayout.createSequentialGroup()
                .addComponent(BtnBuscarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        BtnBuscarLayout.setVerticalGroup(
            BtnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnBuscarCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        txt_buscarCredit.setPreferredSize(new java.awt.Dimension(59, 16));
        jPanel1.add(txt_buscarCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por estados" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 52, 180, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_agregarclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarclienteMouseClicked
        
        ShowPanel(credit);
    }//GEN-LAST:event_txt_agregarclienteMouseClicked

    private void txt_agregarclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarclienteMouseEntered
        AgregarClientBnt.setBackground(new Color(0, 153, 255));
        txt_agregarcliente.setForeground(Color.white);
    }//GEN-LAST:event_txt_agregarclienteMouseEntered

    private void txt_agregarclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarclienteMouseExited
        AgregarClientBnt.setBackground(Color.white);
        txt_agregarcliente.setForeground(Color.black);
    }//GEN-LAST:event_txt_agregarclienteMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        ShowPanel(pagoCredit);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        TblaClientesAtrasados clientAt = new TblaClientesAtrasados();
        ShowPanel(clientAt);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BtnBuscarCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarCreditoMouseClicked
        ctrCr.buscarCreditoPorCedula(txt_buscarCredit.getText().trim());
    }//GEN-LAST:event_BtnBuscarCreditoMouseClicked

    private void BtnBuscarCreditoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarCreditoMouseEntered
        BtnBuscar.setBackground(new Color(0, 153, 255));
        BtnBuscarCredito.setForeground(Color.white);
    }//GEN-LAST:event_BtnBuscarCreditoMouseEntered

    private void BtnBuscarCreditoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarCreditoMouseExited
        BtnBuscar.setBackground(Color.white);
        BtnBuscarCredito.setForeground(Color.black);
    }//GEN-LAST:event_BtnBuscarCreditoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarClientBnt;
    private javax.swing.JPanel BtnBuscar;
    private javax.swing.JLabel BtnBuscarCredito;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_creditos;
    private javax.swing.JPanel transacc;
    private javax.swing.JLabel txt_agregarcliente;
    private javax.swing.JTextField txt_buscarCredit;
    // End of variables declaration//GEN-END:variables

public void CargarTablaCredito() {
        Connection con = Conexionmy.Conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT c.id_credito, cl.nombre, cl.cedula, c.monto, c.interes, c.cuotas, c.valor_cuota, c.monto_total,"
                + "c.saldo_pendiente, c.fecha_inicio, c.fecha_fin, c.estado" +
                 " FROM creditos c " +
                 "INNER JOIN clientes cl ON c.id_cliente = cl.id_cliente;";
        Statement st;

        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            model.addColumn("N°");
            model.addColumn("Nombre");
            model.addColumn("Cedula");
            model.addColumn("Monto");
            model.addColumn("Interes");
            model.addColumn("Cuotas");
            model.addColumn("Valor cuota");
            model.addColumn("Monto total");
            model.addColumn("Saldo Pendiente");
            model.addColumn("Fecha inicio");
            model.addColumn("Fecha fin");
            model.addColumn("Estado");

            while (rs.next()) {

                Object fila[] = new Object[12];
                for (int i = 0; i < 12; i++) {
                    fila[i] = rs.getObject(i + 1);

                }

                model.addRow(fila);
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar tabla Creditos" + e);
        }
        jTable_creditos.setModel(model);
        

        jTable_creditos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_creditos.rowAtPoint(e.getPoint());
                int columna_point = 0;
                int selectedRow = jTable_creditos.getSelectedRow();

                if (fila_point >= 0) {
                    id_credito = (int) jTable_creditos.getValueAt(selectedRow, 0);
//                    act.PasaridCliente(id_cliente);
//                    act.EnviarDatosClienteSeleccionada(id_cliente);
//                    
                    //EnviarDatosClienteSeleccionada(idCliente);

                }
            }
        });
    }

private void ShowPanel(JPanel p) {
        p.setSize(600, 180);
        p.setLocation(0, 0);
        transacc.removeAll();
        transacc.setLayout(new BorderLayout());
        transacc.add(p, BorderLayout.CENTER);
        transacc.revalidate();
        transacc.repaint();

    }



}
