/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Modelos.Creditos;
import java.awt.print.PrinterException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author Bryan
 */
public class HistorialDePagos extends javax.swing.JPanel {

    /**
     * Creates new form HistorialDePagos
     */
    private List<Creditos> listaCreditos = new ArrayList<>();
    private int id_cliente;
    private int id_credito = 0;

    public HistorialDePagos() {
        initComponents();
        //cargarHistorialPagos(id_credito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_HistorialPagos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_buscarCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_cedulaCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_cred = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_estado = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_HistorialPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pago", "Fecha de Pago", "Monto Pagado", "Saldo restante"
            }
        ));
        jScrollPane1.setViewportView(jTable_HistorialPagos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 750, 290));

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HISTORIAL DE PAGOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 300, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("  Ingrese cedula:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        txt_buscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarCedulaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_buscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

        jLabel2.setText("             Datos del cliente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, -1));
        jPanel2.add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));
        jPanel2.add(txt_cedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));

        jLabel4.setText("          Informacion de creditos del cliente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 250, -1));

        jLabel5.setText("Seleccione el credito:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 120, -1));

        jComboBox_cred.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel2.add(jComboBox_cred, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 160, -1));

        jLabel6.setText("             Ver historial de pago");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 190, 30));

        jLabel7.setText("Estado:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        jComboBox_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagado", "Atrasado", "Pendiente" }));
        jComboBox_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_estadoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 750, 160));

        jButton1.setText("Imprimir Historial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarCedulaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String estadoSeleccionado = (String) jComboBox_estado.getSelectedItem();
        buscarUsuarioPorCedula(txt_buscarCedula.getText().trim(), estadoSeleccionado);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int index = jComboBox_cred.getSelectedIndex();
        if (index >= 0 && index < listaCreditos.size()) {
            // Obtener el crédito seleccionado desde la lista
            Creditos creditoSeleccionado = listaCreditos.get(index);
            int idCredito = creditoSeleccionado.getId();

            // Llamar al método que carga el historial
            cargarHistorialPagos(idCredito);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jComboBox_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_estadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        boolean completo = jTable_HistorialPagos.print(
                JTable.PrintMode.FIT_WIDTH, 
                new MessageFormat("Historial de Pagos"), 
                new MessageFormat("Página - {0}")
        );

        if (completo) {
            JOptionPane.showMessageDialog(null, "Impresión completada correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "Impresión cancelada por el usuario.");
        }
    } catch (PrinterException e) {
        JOptionPane.showMessageDialog(null, "Error al imprimir: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_cred;
    private javax.swing.JComboBox<String> jComboBox_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_HistorialPagos;
    private javax.swing.JTextField txt_buscarCedula;
    private javax.swing.JTextField txt_cedulaCliente;
    private javax.swing.JTextField txt_nombreCliente;
    // End of variables declaration//GEN-END:variables

    public void cargarHistorialPagos(int idCredito) {
        String sql = "SELECT p.id_pago, p.fecha_pago, p.monto_pagado, p.saldo_pendiente "
                + "FROM pagos p "
                + "INNER JOIN creditos cr ON cr.id_credito = p.id_credito "
                + "WHERE p.id_credito = ? "
                + "ORDER BY p.fecha_pago DESC";

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID Pago", "Fecha de Pago", "Monto Pagado", "Saldo restante"});

        try (Connection con = Conexion.Conexionmy.Conectar(); PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setInt(1, idCredito);
            ResultSet rs = pst.executeQuery();
            boolean hayPago = false;
            while (rs.next()) {
                hayPago = true;
                model.addRow(new Object[]{
                    rs.getInt("id_pago"),
                    rs.getDate("fecha_pago"),
                    rs.getDouble("monto_pagado"),
                    rs.getString("saldo_pendiente")
                });
            }

            jTable_HistorialPagos.setModel(model);

            if (!hayPago) {
                JOptionPane.showMessageDialog(null, "No se a realizado ningun pago al credito seleccionado");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar historial de pagos: " + e.getMessage());
        }
    }

// public void buscarUsuarioPorCedula(String cedula) {
//        
//        Connection con = Conexionmy.Conectar();
//        String BuscarUser = cedula.trim();
//
//        if (BuscarUser.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Seleccione cliente");
//            return; // No hacer búsqueda si está vacío
//        }
//
//        //Consulta con INNER JOIN para traer cliente y sus créditos
//        String sql = "SELECT c.id_cliente, c.nombre, c.cedula,cr.valor_cuota, "
//                + "cr.id_credito, cr.monto, cr.cuotas, cr.saldo_pendiente "
//                + "FROM clientes c "
//                + "INNER JOIN creditos cr ON c.id_cliente = cr.id_cliente "
//                + "WHERE c.cedula LIKE ?;";
//
//        try {
//            PreparedStatement pst = con.prepareStatement(sql);
//            pst.setString(1, "%" + BuscarUser + "%");
//
//            ResultSet rs = pst.executeQuery();
//            
//
//            // Limpiamos combo antes de cargar
//            jComboBox_cred.removeAllItems();
//            listaCreditos.clear();
//            ///jComboBox_Creditos.addItem("Seleccione");
//            
//            if(!rs.isBeforeFirst()){
//                JOptionPane.showMessageDialog(null, "Cliente no existe o cedula mal ingresada");
//            }else{
//                while (rs.next()) {
//                    double saldoPendiente = rs.getDouble("saldo_pendiente");
//                    if (saldoPendiente >= 0.0) {
//                        // Mostrar solo 1 vez los datos del cliente
//                        id_cliente = rs.getInt("id_cliente");
//                        txt_nombreCliente.setText(rs.getString("nombre"));
//                        txt_cedulaCliente.setText(rs.getString("cedula"));
//
//                        // Guardar todos los datos del crédito en el combo
//                        Creditos credito = new Creditos(
//                                rs.getInt("id_credito"),
//                                rs.getDouble("monto"),
//                                rs.getInt("cuotas"),
//                                rs.getDouble("saldo_pendiente"),
//                                rs.getDouble("valor_cuota"));
//                        
//
//                        listaCreditos.add(credito);
//                        //jComboBox_Creditos.addItem(credito);
//
//                        jComboBox_cred.addItem(credito.getMonto() + " - Crédito #" + credito.getId());
//                    } else {
//                        System.out.println("cliente no tien creditos activos");
//                        //JOptionPane.showMessageDialog(null,"Cliente no existe" );
//                    }
//
//                }
//                if (listaCreditos.isEmpty()) {
//                    JOptionPane.showMessageDialog(null, "clientes no cuenta con creditos");
//                }
//            }
//            con.close();
//        } catch (SQLException e) {
//            System.out.println("Error al buscar Cliente y sus créditos: " + e);
//        }
//    }
    public void buscarUsuarioPorCedula(String cedula, String estado) {
        Connection con = Conexionmy.Conectar();
        String BuscarUser = cedula.trim();

        if (BuscarUser.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione cliente");
            return;
        }

        String sql = "SELECT c.id_cliente, c.nombre, c.cedula, cr.id_credito, cr.monto, cr.cuotas, cr.saldo_pendiente, cr.valor_cuota "
                + "FROM clientes c "
                + "INNER JOIN creditos cr ON c.id_cliente = cr.id_cliente "
                + "WHERE c.cedula LIKE ?";

        // Agregamos condición de estado
        switch (estado) {
            case "Pendiente":
                sql += " AND cr.estado = 'Pendiente'";
                break;
            case "Pagado":
                sql += " AND cr.estado = 'Pagado'";
                break;
            case "Atrasado":
                sql += " AND cr.estado = 'Atrasado'";
                break;
        }

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, "%" + BuscarUser + "%");
            ResultSet rs = pst.executeQuery();

            jComboBox_cred.removeAllItems();
            listaCreditos.clear();

            if (!rs.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null, "Cliente no existe o cédula mal ingresada");
            } else {
                while (rs.next()) {
                    double saldoPendiente = rs.getDouble("saldo_pendiente");

                    // Agregar solo si cumple filtro de saldo
                    if ("Todos".equals(estado) || saldoPendiente > 0 || saldoPendiente == 0) {
                        id_cliente = rs.getInt("id_cliente");
                        txt_nombreCliente.setText(rs.getString("nombre"));
                        txt_cedulaCliente.setText(rs.getString("cedula"));

                        Creditos credito = new Creditos(
                                rs.getInt("id_credito"),
                                rs.getDouble("monto"),
                                rs.getInt("cuotas"),
                                rs.getDouble("saldo_pendiente"),
                                rs.getDouble("valor_cuota")
                        );

                        listaCreditos.add(credito);
                        jComboBox_cred.addItem(credito.getMonto() + " - Crédito #" + credito.getId());
                    }
                }
            }

            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar Cliente y sus créditos: " + e.getMessage());
        }
    }

}
