/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Controladores.ControladorUsuario;
import Helper.EncrypPassw;
import Modelos.Usuario;
import Modelos.ValidarSesion;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.Clock;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Bryan
 */
public class Login extends javax.swing.JFrame {
    //private static String u="";

    /**
     * Creates new form Login
     */
    
    int xmouse, ymouse;
    public Login() {
        initComponents();
       
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        iniciarSBtn = new javax.swing.JPanel();
        txt_iniciarsesion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        salirBtn = new javax.swing.JPanel();
        txt_salir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(106, 207, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 87, 86));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        txt_Usuario.setBackground(new java.awt.Color(85, 87, 86));
        txt_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_Usuario.setText("Ingrese su usuario");
        txt_Usuario.setBorder(null);
        txt_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_UsuarioMousePressed(evt);
            }
        });
        jPanel2.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, -1));

        txt_contraseña.setBackground(new java.awt.Color(85, 87, 86));
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_contraseña.setText("********");
        txt_contraseña.setToolTipText("");
        txt_contraseña.setBorder(null);
        txt_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contraseñaMousePressed(evt);
            }
        });
        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 190, 10));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 180, 10));

        iniciarSBtn.setBackground(new java.awt.Color(102, 102, 102));
        iniciarSBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarSBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarSBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarSBtnMouseExited(evt);
            }
        });

        txt_iniciarsesion.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        txt_iniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        txt_iniciarsesion.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout iniciarSBtnLayout = new javax.swing.GroupLayout(iniciarSBtn);
        iniciarSBtn.setLayout(iniciarSBtnLayout);
        iniciarSBtnLayout.setHorizontalGroup(
            iniciarSBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarSBtnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txt_iniciarsesion)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        iniciarSBtnLayout.setVerticalGroup(
            iniciarSBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_iniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(iniciarSBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 227, 380, 250));

        jPanel3.setBackground(new java.awt.Color(106, 207, 241));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        salirBtn.setBackground(new java.awt.Color(106, 207, 241));

        txt_salir.setBackground(new java.awt.Color(255, 255, 255));
        txt_salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_salir.setForeground(new java.awt.Color(255, 255, 255));
        txt_salir.setText("     X");
        txt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_salir.setPreferredSize(new java.awt.Dimension(16, 16));
        txt_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salirBtnLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(txt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo pro.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(x - xmouse,Y - ymouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void txt_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txt_salirMouseClicked

    private void txt_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salirMouseEntered
        salirBtn.setBackground(Color.red);
        txt_salir.setForeground(Color.black);
    }//GEN-LAST:event_txt_salirMouseEntered

    private void txt_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salirMouseExited
        salirBtn.setBackground(Color.black);
        txt_salir.setForeground(Color.white);
    }//GEN-LAST:event_txt_salirMouseExited

    private void iniciarSBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarSBtnMouseEntered
        iniciarSBtn.setBackground(Color.black);
        txt_iniciarsesion.setForeground(Color.white);
    }//GEN-LAST:event_iniciarSBtnMouseEntered

    private void iniciarSBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarSBtnMouseExited
        iniciarSBtn.setBackground(Color.gray);
        txt_iniciarsesion.setForeground(Color.black);
    }//GEN-LAST:event_iniciarSBtnMouseExited

    private void iniciarSBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarSBtnMouseClicked
        this.Loginn();
        
    }//GEN-LAST:event_iniciarSBtnMouseClicked

    private void txt_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_UsuarioMousePressed
        if(txt_Usuario.getText().equals("Ingrese su usuario")){
            txt_Usuario.setText("");
            
        }
        if(txt_contraseña.getText().isEmpty()){
            txt_contraseña.setText("********");
        }
    }//GEN-LAST:event_txt_UsuarioMousePressed

    private void txt_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contraseñaMousePressed
        if(txt_contraseña.getText().equals("********")){
            txt_contraseña.setText("");  
        }
        if(txt_Usuario.getText().isEmpty()){
            txt_Usuario.setText("Ingrese su usuario");
        }
    }//GEN-LAST:event_txt_contraseñaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login().setVisible(true);
                Login log  = new Login();
                log.setLocationRelativeTo(null);
                log.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel iniciarSBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JLabel txt_iniciarsesion;
    private javax.swing.JLabel txt_salir;
    // End of variables declaration//GEN-END:variables

private void Loginn() {
        
        
        if (!txt_Usuario.getText().isEmpty() && !txt_contraseña.getText().isEmpty()) {

            ControladorUsuario controlUsuario = new ControladorUsuario();
            Usuario usuario = new Usuario();
            usuario.setNombre(txt_Usuario.getText().trim());
            EncrypPassw encryp = new EncrypPassw();
            String pass = encryp.encriptarSHA256(txt_contraseña.getText().trim());
            usuario.setClave(pass);
            

            if (controlUsuario.login(usuario)) {
                
                ValidarSesion.setRolsesion(usuario.getRol());
                //usuario.setRolSession(usuario.getRol());
                
//                Vista_Menu menu = new Vista_Menu();
//                menu.setVisible(true);
//                this.dispose();
                  Vista_Menu_Prueba menu = new Vista_Menu_Prueba();
                  menu.setLocationRelativeTo(null);
                  menu.setVisible(true);
                  this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "usuario o clave incorrecto");
            }

        } else {
            JOptionPane.showMessageDialog(null, "los campos deben estar completos");

        }
    }



}

