/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorCliente;
import Controladores.ControladorCreditos;
import Helper.EnvioWhatsApp;
import Modelos.Creditos;
import Modelos.PagosCr;
import java.awt.Color;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class RealizarPagoCredito extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCredito
     */
    public String telefono_celular;
    private double monto_pago;
    private String nombre_cliente;
    private CreditosG creditosG;
    private int id_creditoo;
    private List<Creditos> listaCreditos = new ArrayList<>();
    Date fecha_reg = new Date();
    SimpleDateFormat formatear = new SimpleDateFormat("yyyy-MM-dd");
    private int id_cliente;
    ControladorCreditos ctr = new ControladorCreditos();
    private int id_tipo;

    public RealizarPagoCredito(CreditosG creditosG) {
        initComponents();
        this.creditosG = creditosG;
        //CargarTipoCredito();
        //this.creditosG=creditosG;
//        txt_cedulaCliente.setEditable(false);
//        txt_nombreCliente.setEditable(false);
        txt_fechareg.setText(formatear.format(fecha_reg));

    }

    public String GetTxtbuscarCedula() {
        return txt_buscarCedula.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ingreseCedulaBtn = new javax.swing.JPanel();
        txt_ingreseCedula = new javax.swing.JLabel();
        txt_buscarCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_cedulaCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Creditos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cuotaF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_totalconI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_fechareg = new javax.swing.JTextField();
        agregarPagoBtn = new javax.swing.JPanel();
        txt_agregarPago = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_observaciones = new javax.swing.JTextField();
        calcularBtn = new javax.swing.JPanel();
        txt_calcular = new javax.swing.JLabel();
        txt_numeroCuotas = new javax.swing.JTextField();
        txt_pendientesfecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setPreferredSize(new java.awt.Dimension(770, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreseCedulaBtn.setBackground(new java.awt.Color(204, 204, 204));

        txt_ingreseCedula.setText("  Ingrese cedula");
        txt_ingreseCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ingreseCedulaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ingreseCedulaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ingreseCedulaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingreseCedulaBtnLayout = new javax.swing.GroupLayout(ingreseCedulaBtn);
        ingreseCedulaBtn.setLayout(ingreseCedulaBtnLayout);
        ingreseCedulaBtnLayout.setHorizontalGroup(
            ingreseCedulaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ingreseCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ingreseCedulaBtnLayout.setVerticalGroup(
            ingreseCedulaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ingreseCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jPanel1.add(ingreseCedulaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, -1));
        jPanel1.add(txt_buscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 7, 126, -1));

        jLabel2.setText("           Datos del cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 35, 171, -1));

        txt_nombreCliente.setEditable(false);
        jPanel1.add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, 115, -1));

        txt_cedulaCliente.setEditable(false);
        jPanel1.add(txt_cedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 57, 112, -1));

        jLabel3.setText("Credito a pagar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        jComboBox_Creditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox_Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_CreditosMouseClicked(evt);
            }
        });
        jComboBox_Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CreditosActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 116, -1));

        jLabel4.setText("Numero de cuotas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 111, -1));

        jLabel5.setText("Monto total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 72, -1));

        jLabel6.setText("Monto a pagar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 90, -1));
        jPanel1.add(txt_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 230, -1));

        jLabel7.setText("Cuotas restantes:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 90, -1));

        txt_cuotaF.setEditable(false);
        jPanel1.add(txt_cuotaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 55, -1));

        jLabel8.setText("pendiente:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        txt_totalconI.setEditable(false);
        jPanel1.add(txt_totalconI, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 92, -1));

        jLabel9.setText("Fecha registro:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 86, -1));

        txt_fechareg.setEditable(false);
        txt_fechareg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecharegActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fechareg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 230, -1));

        agregarPagoBtn.setBackground(new java.awt.Color(255, 255, 255));
        agregarPagoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_agregarPago.setText("   Agregar pago");
        txt_agregarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_agregarPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_agregarPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_agregarPagoMouseExited(evt);
            }
        });
        agregarPagoBtn.add(txt_agregarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(agregarPagoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 101, 30));

        jLabel12.setText("Obesrvacion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));
        jPanel1.add(txt_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 230, -1));

        calcularBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_calcular.setText("          Calcular");
        txt_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_calcularMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_calcularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_calcularMouseExited(evt);
            }
        });

        javax.swing.GroupLayout calcularBtnLayout = new javax.swing.GroupLayout(calcularBtn);
        calcularBtn.setLayout(calcularBtnLayout);
        calcularBtnLayout.setHorizontalGroup(
            calcularBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        calcularBtnLayout.setVerticalGroup(
            calcularBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(calcularBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, 30));

        txt_numeroCuotas.setEditable(false);
        jPanel1.add(txt_numeroCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, -1));

        txt_pendientesfecha.setEditable(false);
        jPanel1.add(txt_pendientesfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 110, -1));

        jLabel1.setText("      Ver credito");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ingreseCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingreseCedulaMouseClicked

        buscarUsuarioPorCedula(txt_buscarCedula.getText());
        txt_buscarCedula.setText("");


    }//GEN-LAST:event_txt_ingreseCedulaMouseClicked

    private void txt_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_calcularMouseClicked

        if (!txt_nombreCliente.getText().trim().isEmpty()) {
            int indices = jComboBox_Creditos.getSelectedIndex();
            Creditos seleccionadoss = listaCreditos.get(indices);
            if (!txt_monto.getText().trim().isEmpty()) {
                if (seleccionadoss.getSaldoPendiente() >= Double.parseDouble(txt_monto.getText().trim())) {

                    calcularClcularPago();
                } else {
                    JOptionPane.showMessageDialog(this, "El valor del pago es mayor al valor a cancelar.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un monto a pagar.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
        }
//        calcularCredito();
//        calcularFechaFin();


    }//GEN-LAST:event_txt_calcularMouseClicked

    private void txt_agregarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarPagoMouseClicked

        PagosCr pago = new PagosCr();
        Creditos creddd = new Creditos();
        pago.setIdCredito(id_creditoo);
        jComboBox_Creditos.addItem("Seleccione");

        if (!txt_nombreCliente.getText().trim().isEmpty() && !txt_cedulaCliente.getText().trim().isEmpty()) {
            pago.setMontoPago(Double.parseDouble(txt_monto.getText().trim().replace(",", ".")));
            try {
                pago.setFechaPago(formatear.parse(txt_fechareg.getText().trim()));
            } catch (Exception ex) {
                System.out.println("error en el parseo de la fecha" + ex);
            }
            pago.setNumCuota(Integer.parseInt(txt_numeroCuotas.getText().trim()));
            pago.setObservanes(txt_observaciones.getText().trim());
            pago.setSaldo_pendiente(Double.parseDouble(txt_totalconI.getText().trim()));
            ctr.guardarPago(pago);
            creddd.setCuotas(Integer.parseInt(txt_cuotaF.getText().trim()));
            creddd.setSaldoPendiente(Double.parseDouble(txt_totalconI.getText().trim()));
            ctr.actualizarCredito(creddd, id_creditoo);
            JOptionPane.showMessageDialog(null, "Pago exitoso");
            creditosG.CargarTablaCredito();
            
            
            
            monto_pago = Double.parseDouble(txt_monto.getText().trim());
            String numeroCliente = telefono_celular; // sin 0 inicial y sin +
            numeroCliente = numeroCliente.substring(1);
            String mensaje = "Hola "+ nombre_cliente+", tu pago de "+ monto_pago +" fue registrado exitosamente. ¡Gracias por confiar en nosotros!";
            String numeroWhatsApp = "593" + numeroCliente;
            System.out.println(numeroWhatsApp);

            //EnvioWhatsApp.enviarMensaje(numeroWhatsApp, mensaje);
                EnvioWhatsApp enviar = new EnvioWhatsApp();
                enviar.enviarMensajeWhatsApp(numeroWhatsApp, mensaje);

            if (creddd.getSaldoPendiente() == 0) {
                ctr.actualizarEstado("pagado", id_creditoo);
                creditosG.CargarTablaCredito();
                JOptionPane.showMessageDialog(null, "Termino su credito");
                this.Limpiar();
            }
            this.Limpiar();

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente para realizar pago");
        }

    }//GEN-LAST:event_txt_agregarPagoMouseClicked

    private void txt_fecharegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecharegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecharegActionPerformed

    private void txt_agregarPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarPagoMouseEntered
        agregarPagoBtn.setBackground(new Color(0, 153, 255));
        txt_agregarPago.setForeground(Color.white);
    }//GEN-LAST:event_txt_agregarPagoMouseEntered

    private void txt_agregarPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarPagoMouseExited
        agregarPagoBtn.setBackground(Color.white);
        txt_agregarPago.setForeground(Color.black);
    }//GEN-LAST:event_txt_agregarPagoMouseExited

    private void txt_calcularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_calcularMouseEntered
        calcularBtn.setBackground(new Color(0, 153, 255));
        txt_calcular.setForeground(Color.white);
    }//GEN-LAST:event_txt_calcularMouseEntered

    private void txt_calcularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_calcularMouseExited
        calcularBtn.setBackground(Color.white);
        txt_calcular.setForeground(Color.black);
    }//GEN-LAST:event_txt_calcularMouseExited

    private void txt_ingreseCedulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingreseCedulaMouseEntered
        ingreseCedulaBtn.setBackground(new Color(0, 153, 255));
        txt_ingreseCedula.setForeground(Color.white);
    }//GEN-LAST:event_txt_ingreseCedulaMouseEntered

    private void txt_ingreseCedulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingreseCedulaMouseExited
        ingreseCedulaBtn.setBackground(Color.white);
        txt_ingreseCedula.setForeground(Color.black);
    }//GEN-LAST:event_txt_ingreseCedulaMouseExited

    private void jComboBox_CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_CreditosMouseClicked
//        String montoC = (String) jComboBox_Creditos.getSelectedItem();
//         if (!montoC.equals("Seleccione")) {
//        mostrarDetalleCredito(Double.parseDouble(montoC));
//        }else{
//             JOptionPane.showMessageDialog(null, "Seleccione un credito");
//         }
    }//GEN-LAST:event_jComboBox_CreditosMouseClicked

    private void jComboBox_CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_CreditosActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int indice = jComboBox_Creditos.getSelectedIndex();
        if (indice >= 0) {
            Creditos seleccionado = listaCreditos.get(indice); // obtenemos el objeto real
            id_creditoo = seleccionado.getId();
            txt_numeroCuotas.setText(String.valueOf(seleccionado.getCuotas()));
            txt_pendientesfecha.setText(String.valueOf(seleccionado.getSaldoPendiente()));
            txt_monto.setText(String.valueOf(seleccionado.getValorCuota()));

        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarPagoBtn;
    private javax.swing.JPanel calcularBtn;
    private javax.swing.JPanel ingreseCedulaBtn;
    private javax.swing.JComboBox<String> jComboBox_Creditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel txt_agregarPago;
    private javax.swing.JTextField txt_buscarCedula;
    private javax.swing.JLabel txt_calcular;
    private javax.swing.JTextField txt_cedulaCliente;
    private javax.swing.JTextField txt_cuotaF;
    private javax.swing.JTextField txt_fechareg;
    private javax.swing.JLabel txt_ingreseCedula;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_numeroCuotas;
    private javax.swing.JTextField txt_observaciones;
    private javax.swing.JTextField txt_pendientesfecha;
    private javax.swing.JTextField txt_totalconI;
    // End of variables declaration//GEN-END:variables

    public void calcularClcularPago() {
        try {
            // Obtener el crédito seleccionado del combo
            //Creditos credito = (Creditos) jComboBox_Creditos.getSelectedItem();
            int indices = jComboBox_Creditos.getSelectedIndex();
            //System.out.println("indice" + indices);
            Creditos seleccionadoss = listaCreditos.get(indices);
            //System.out.println("indice" + seleccionadoss);

//            if (indices <= 0) {
//                JOptionPane.showMessageDialog(this, "Debe seleccionar un crédito.");
//                return;
//            }
            // Obtener monto ingresado
            double montoPago = Double.parseDouble(txt_monto.getText().trim());

            // Restar del saldo pendiente
            double nuevoSaldo = seleccionadoss.getSaldoPendiente() - montoPago;
            double mitadPago = seleccionadoss.getSaldoPendiente() / 2;
            // Restar una cuota
            int nuevasCuotas = seleccionadoss.getCuotas() - 1;

            // Mostrar en los campos
            if (seleccionadoss.getSaldoPendiente() == montoPago) {
                txt_cuotaF.setText(String.valueOf(0));
                txt_totalconI.setText(String.format("%.2f", nuevoSaldo).replace(",", "."));

            } else {
                txt_totalconI.setText(String.format("%.2f", nuevoSaldo).replace(",", "."));

                txt_cuotaF.setText(String.valueOf(nuevasCuotas));
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.");
        }
    }

//    private void CargarTipoCredito() {
//        Connection cn = Conexion.Conexionmy.Conectar();
//        String sql = "select * from tipo_credito";
//        Statement st;
//
//        try {
//
//            st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            jComboBox_Creditos.removeAllItems();
//            jComboBox_Creditos.addItem("Seleccione");
//            while (rs.next()) {
//                jComboBox_Creditos.addItem(rs.getString("tipo"));
//
//            }
//            cn.close();
//
//        } catch (SQLException e) {
//            System.out.println("Error al cargar tipo de credito" + e);
//        }
//
//    }
//    private void obtenerIdTipo() {
//        try {
//            String sql = "select * from tipo_credito where tipo ='" + this.jComboBox_Creditos.getSelectedItem() + "'";
//            Connection cn = Conexion.Conexionmy.Conectar();
//            Statement st;
//            st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//
//            while (rs.next()) {
//                id_tipo = rs.getInt("idClientes");
//
//            }
//
//        } catch (SQLException e) {
//            System.out.println("ERROR AL OBTENER ID DEL TIPO:" + e);
//        }
//    }
    public void buscarUsuarioPorCedula(String cedula) {

        Connection con = Conexionmy.Conectar();
        String BuscarUser = cedula.trim();

        if (BuscarUser.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione cliente");
            return; // No hacer búsqueda si está vacío
        }

        //Consulta con INNER JOIN para traer cliente y sus créditos
        String sql = "SELECT c.id_cliente, c.nombre, c.cedula,cr.valor_cuota, c.telefono, "
                + "cr.id_credito, cr.monto, cr.cuotas, cr.saldo_pendiente "
                + "FROM clientes c "
                + "INNER JOIN creditos cr ON c.id_cliente = cr.id_cliente "
                + "WHERE c.cedula LIKE ?;";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, "%" + BuscarUser + "%");

            ResultSet rs = pst.executeQuery();

            // Limpiamos combo antes de cargar
            jComboBox_Creditos.removeAllItems();
            listaCreditos.clear();
            ///jComboBox_Creditos.addItem("Seleccione");

            if (!rs.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null, "Cliente no existe o cedula mal ingresada");
            } else {
                while (rs.next()) {
                    double saldoPendiente = rs.getDouble("saldo_pendiente");
                    if (saldoPendiente > 0.0) {
                        // Mostrar solo 1 vez los datos del cliente
                        id_cliente = rs.getInt("id_cliente");
                        telefono_celular = rs.getString("telefono");
                        nombre_cliente= rs.getString("nombre");
                        txt_nombreCliente.setText(rs.getString("nombre"));
                        txt_cedulaCliente.setText(rs.getString("cedula"));

                        // Guardar todos los datos del crédito en el combo
                        Creditos credito = new Creditos(
                                rs.getInt("id_credito"),
                                rs.getDouble("monto"),
                                rs.getInt("cuotas"),
                                rs.getDouble("saldo_pendiente"),
                                rs.getDouble("valor_cuota"));

                        listaCreditos.add(credito);
                        //jComboBox_Creditos.addItem(credito);

                        jComboBox_Creditos.addItem(credito.getMonto() + " - Crédito #" + credito.getId());
                    } else {
                        System.out.println("cliente no tien creditos activos");
                        //JOptionPane.showMessageDialog(null,"Cliente no existe" );
                    }

                }
                if (listaCreditos.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "clientes no cuenta con creditos");
                }
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al buscar Cliente y sus créditos: " + e);
        }
    }

    public void Limpiar() {
        txt_cedulaCliente.setText("");
        txt_buscarCedula.setText("");
        txt_cuotaF.setText("");
        txt_numeroCuotas.setText("");
        txt_pendientesfecha.setText("");
        txt_fechareg.setText(formatear.format(fecha_reg));

        txt_monto.setText("");
        txt_nombreCliente.setText("");
        txt_observaciones.setText("");
        txt_totalconI.setText("");
        //jSpinner_cuotas.setValue(0);

        jComboBox_Creditos.setSelectedItem("Seleccione");
        //jComboBox_interes.setSelectedItem("Seleccione");
        
        
    }
}
