/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import static Ventanas.ClientesG.jTable_cliente;
import java.sql.PreparedStatement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class TblaClientesAtrasados extends javax.swing.JPanel {
    private String nombreCliente;
    private String cedulaCliente;
    private String telefonoCliente;
    private String direccionCliente;
    public String CorreoCliente;
    public int idCredito;
    public int idCliente;
    public int id_credito;

    private String fechaActual = "";
    private String nombreArchinoFinal = "";
    ActualizarCredito ActualizarCred = new ActualizarCredito(this);

    /**
     * Creates new form TblaClientesAtrasados
     */
    public TblaClientesAtrasados() {
        
        initComponents();
        cargarClientesConCuotasAtrasadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Atrasados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_actualizarTabla = new javax.swing.JPanel();
        txt_actualizarTabla = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_buscarAtrasado = new javax.swing.JTextField();
        Refinanciar_Panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Atrasados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Atrasados);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1010, 220));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("CLIENTES EN RIESGO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 270, 40));

        btn_actualizarTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btn_actualizarTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_actualizarTabla.setText("            Actualizar tabla");
        txt_actualizarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_actualizarTablaMouseClicked(evt);
            }
        });
        btn_actualizarTabla.add(txt_actualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel1.add(btn_actualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 160, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("        Buscar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 30));

        txt_buscarAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarAtrasadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_buscarAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 150, 30));

        Refinanciar_Panel.setBackground(new java.awt.Color(231, 250, 250));
        jPanel1.add(Refinanciar_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 750, 230));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("               Recuperar cliente");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 180, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_actualizarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizarTablaMouseClicked
        cargarClientesConCuotasAtrasadas();
    }//GEN-LAST:event_txt_actualizarTablaMouseClicked

    private void txt_buscarAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarAtrasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarAtrasadoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        buscarClienteAtrasadoPorCedula(txt_buscarAtrasado.getText().trim());
        txt_buscarAtrasado.setText("");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        ShowPanel(ActualizarCred);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Refinanciar_Panel;
    private javax.swing.JPanel btn_actualizarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Atrasados;
    private javax.swing.JLabel txt_actualizarTabla;
    private javax.swing.JTextField txt_buscarAtrasado;
    // End of variables declaration//GEN-END:variables



//public void cargarClientesConCuotasAtrasadas() {
//    String sql = "SELECT " +
//             "MAX(p.fecha_pago) AS ultima_fecha_pago," +
//             "cl.id_cliente, cl.nombre, cl.cedula,c.id_credito,cl.telefono,cl.direccion, " +
//             "c.monto,c.tipo_credito, c.valor_cuota, c.fecha_inicio, c.cuotas, " +
//             "((CASE " +
//             "WHEN c.tipo_credito = 2 THEN DATEDIFF(CURDATE(), c.fecha_inicio) " +
//             "WHEN c.tipo_credito = 3 THEN FLOOR(DATEDIFF(CURDATE(), c.fecha_inicio)/7) " +
//             "WHEN c.tipo_credito = 1 THEN TIMESTAMPDIFF(MONTH, c.fecha_inicio, CURDATE()) " +
//             "END) - IFNULL(COUNT(p.id_pago), 0)) AS cuotas_atrasadas " +  // ← usamos IFNULL
//             "FROM creditos c " +
//             "INNER JOIN clientes cl ON c.id_cliente = cl.id_cliente " +
//             "LEFT JOIN pagos p ON c.id_credito = p.id_credito AND (p.fecha_pago <= CURDATE() OR p.fecha_pago IS NULL) " +
//             "GROUP BY c.id_credito " +
//             "HAVING cuotas_atrasadas > 0";
//
//
//
//    DefaultTableModel model = new DefaultTableModel();
//    model.setColumnIdentifiers(new Object[]{
//    "Última Fecha de Pago", "id_cliente", "Nombre", "Cédula",
//    "id_credito", "telefono", "direccion", "Monto de credito",
//    "Tipo Crédito", "valor de cuotas","fecha_inicio","cuotas","cuotas_atrasadas"
//});
//
//
//    try (Connection con = Conexion.Conexionmy.Conectar();
//         PreparedStatement pst = con.prepareStatement(sql);
//         ResultSet rs = pst.executeQuery()) {
//
//        while (rs.next()) {
//            Object[] fila = new Object[13];
//            for (int i = 0; i < 13; i++) {
//                fila[i] = rs.getObject(i + 1);
//            }
//            model.addRow(fila);
//            
//             idCredito = rs.getInt("id_credito");
//             nombreCliente = rs.getString("nombre");
//             cedulaCliente = rs.getString("cedula");
//             telefonoCliente = rs.getString("telefono");
//             direccionCliente = rs.getString("direccion");
//             idCliente = rs.getInt("id_cliente");
//            System.out.println(idCredito);
//            System.out.println(nombreCliente);
//            System.out.println(telefonoCliente);
//            System.out.println(direccionCliente);
//            
//            
//            actualizarEstadoCliente(idCredito, "Atrasado"); 
//        }
//
//        jTable_Atrasados.setModel(model);
//
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(null, "Error al cargar clientes con cuotas atrasadas: " + e.getMessage());
//    }
//
//}

    
    
    
    public void cargarClientesConCuotasAtrasadas() {
    String sql = "SELECT " +
                 "c.id_credito, " +
                 "cl.id_cliente, cl.nombre, cl.cedula,MAX(p.fecha_pago) AS ultima_fecha_pago , cl.telefono, cl.direccion, " +
                 "c.monto, c.tipo_credito, c.valor_cuota, c.fecha_inicio, c.cuotas, " +
                 "((CASE " +
                 "   WHEN c.tipo_credito = 2 THEN DATEDIFF(CURDATE(), c.fecha_inicio) " +
                 "   WHEN c.tipo_credito = 3 THEN FLOOR(DATEDIFF(CURDATE(), c.fecha_inicio)/7) " +
                 "   WHEN c.tipo_credito = 1 THEN TIMESTAMPDIFF(MONTH, c.fecha_inicio, CURDATE()) " +
                 " END) - IFNULL(COUNT(p.id_pago), 0)) AS cuotas_atrasadas, " +
                 "c.saldo_pendiente " +
                 "FROM creditos c " +
                 "INNER JOIN clientes cl ON c.id_cliente = cl.id_cliente " +
                 "LEFT JOIN pagos p ON c.id_credito = p.id_credito AND (p.fecha_pago <= CURDATE() OR p.fecha_pago IS NULL) " +
                 "GROUP BY c.id_credito " + 
                 "HAVING cuotas_atrasadas > 0 AND saldo_pendiente > 0"; // Solo créditos con saldo pendiente

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{
        "id_credito", "id_cliente", "Nombre", "Cédula",
        "Última Fecha de Pago", "telefono", "direccion", "Monto de credito",
        "Tipo Crédito", "valor de cuotas", "fecha_inicio", "cuotas",
        "cuotas_atrasadas", "saldo_pendiente"
    });

    try (Connection con = Conexion.Conexionmy.Conectar();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            Object[] fila = new Object[14]; 
            for (int i = 0; i < 14; i++) {
                fila[i] = rs.getObject(i + 1);
            }

            double saldoPendiente = rs.getDouble("saldo_pendiente");

            if (saldoPendiente > 0) { // Solo agregar si hay saldo pendiente
                model.addRow(fila);

                int idCredito = rs.getInt("id_credito");
                actualizarEstadoCliente(idCredito, "Atrasado");
            }
        }

        jTable_Atrasados.setModel(model);
        
        jTable_Atrasados.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_Atrasados.rowAtPoint(e.getPoint());
                int columna_point = 0;
                int selectedRow = jTable_Atrasados.getSelectedRow();

                if (fila_point >= 0) {
                    id_credito = Integer.parseInt(jTable_Atrasados.getValueAt(selectedRow, 0).toString());
                    //System.out.println(id_credito);
                    //act.PasaridCliente(id_cliente);
                    ActualizarCred.EnviarDatosClienteSeleccionados(id_credito);
                    
                    //EnviarDatosClienteSeleccionada(idCliente);

                }
            }
        });

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar clientes con cuotas atrasadas: " + e.getMessage());
    }
}
    
    
       

    
    
    



public boolean actualizarEstadoCliente(int idCredito, String nuevoEstado) {
    String sql = "UPDATE creditos SET estado = ? WHERE id_credito = ?";
    try (Connection conn = Conexionmy.Conectar();  
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, nuevoEstado);
        ps.setInt(2, idCredito);

        int filasActualizadas = ps.executeUpdate();
        //System.out.println("actualizado exitoso");

        boolean isok =  filasActualizadas > 0; 
        return isok;
        
    } catch (SQLException e) {
        System.out.println("Error al actualizar el estado del cliente: " + e.getMessage());
        return false;
    }
}


public void buscarClienteAtrasadoPorCedula(String cedulaBuscada) {
    String sql = "SELECT " +
             "c.id_credito, " +
             "cl.id_cliente, cl.nombre, cl.cedula, MAX(p.fecha_pago) AS ultima_fecha_pago , cl.telefono, cl.direccion, " +
             "c.monto, c.tipo_credito, c.valor_cuota, c.fecha_inicio, c.cuotas, " +
             "((CASE " +
             "WHEN c.tipo_credito = 2 THEN DATEDIFF(CURDATE(), c.fecha_inicio) " +
             "WHEN c.tipo_credito = 3 THEN FLOOR(DATEDIFF(CURDATE(), c.fecha_inicio)/7) " +
             "WHEN c.tipo_credito = 1 THEN TIMESTAMPDIFF(MONTH, c.fecha_inicio, CURDATE()) " +
             "END) - IFNULL(COUNT(p.id_pago), 0)) AS cuotas_atrasadas " +
             "FROM creditos c " +
             "INNER JOIN clientes cl ON c.id_cliente = cl.id_cliente " +
             "LEFT JOIN pagos p ON c.id_credito = p.id_credito " +
             "WHERE c.estado = 'Atrasado' AND cl.cedula = ? " + // ← buscar solo atrasados por cédula
             "GROUP BY c.id_credito " +
             "HAVING cuotas_atrasadas > 0";

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{
        "id_credito", "id_cliente", "Nombre", "Cédula",
        "Última Fecha de Pago", "telefono", "direccion", "Monto de crédito",
        "Tipo Crédito", "valor de cuota", "fecha_inicio", "cuotas", "cuotas_atrasadas"
    });

    try (Connection con = Conexion.Conexionmy.Conectar();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, cedulaBuscada); // ← usuario ingresa la cédula
        ResultSet rs = pst.executeQuery();

        boolean encontrado = false;

        while (rs.next()) {
            encontrado = true;
            Object[] fila = new Object[13];
            for (int i = 0; i < 13; i++) {
                fila[i] = rs.getObject(i + 1);
            }
            model.addRow(fila);

            
        }

        jTable_Atrasados.setModel(model);

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "No se encontró ningún cliente atrasado con esa cédula.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al buscar cliente atrasado: " + e.getMessage());
    }
}




private void ShowPanel(JPanel p) {
        p.setSize(600, 180);
        p.setLocation(0, 0);
        Refinanciar_Panel.removeAll();
        Refinanciar_Panel.setLayout(new BorderLayout());
        Refinanciar_Panel.add(p, BorderLayout.CENTER);
        Refinanciar_Panel.revalidate();
        Refinanciar_Panel.repaint();

    }




}
