/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import static Ventanas.ClientesG.jTable_cliente;
import java.sql.PreparedStatement;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class TblaClientesAtrasados extends javax.swing.JPanel {

    /**
     * Creates new form TblaClientesAtrasados
     */
    public TblaClientesAtrasados() {
        initComponents();
        cargarClientesConCuotasAtrasadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Atrasados = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Atrasados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Atrasados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 210));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Atrasados;
    // End of variables declaration//GEN-END:variables



public void cargarClientesConCuotasAtrasadas() {
    String sql = "SELECT c.id_credito, cl.id_cliente, cl.nombre, cl.cedula, c.monto, c.cuotas, c.valor_cuota, c.fecha_inicio, c.tipo_credito, " +
                 "((CASE " +
                 "WHEN c.tipo_credito = 2 THEN DATEDIFF(CURDATE(), c.fecha_inicio) " +
                 "WHEN c.tipo_credito = 3 THEN FLOOR(DATEDIFF(CURDATE(), c.fecha_inicio)/7) " +
                 "WHEN c.tipo_credito = 1 THEN TIMESTAMPDIFF(MONTH, c.fecha_inicio, CURDATE()) " +
                 "END) - COUNT(p.id_pago)) AS cuotas_atrasadas " +
                 "FROM creditos c " +
                 "INNER JOIN clientes cl ON c.id_cliente = cl.id_cliente " +
                 "LEFT JOIN pagos p ON c.id_credito = p.id_credito AND p.fecha_pago <= CURDATE() " +
                 "GROUP BY c.id_credito " +
                 "HAVING cuotas_atrasadas > 0";

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"ID Credito", "ID Cliente", "Nombre", "Cédula", "Monto", "Cuotas", "Valor Cuota", "Fecha Inicio", "Tipo Crédito", "Cuotas Atrasadas"});

    try (Connection con = Conexion.Conexionmy.Conectar();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            Object[] fila = new Object[10];
            for (int i = 0; i < 10; i++) {
                fila[i] = rs.getObject(i + 1);
            }
            model.addRow(fila);
        }

        jTable_Atrasados.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar clientes con cuotas atrasadas: " + e.getMessage());
    }

}

}
