/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Conexion.Conexionmy;
import Controladores.ControladorUsuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan
 */
public class UsuarioG extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioG
     */
    private int id_cliente;
    ControladorUsuario user = new ControladorUsuario();
    ActualizarUser act = new ActualizarUser(this);
    AgregarUser addUser= new AgregarUser(this);

    public UsuarioG() {
        initComponents();
        CargarTablaUsuario();

    }

    public int GetIdCliente() {
        return id_cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarUsuarioBtn = new javax.swing.JPanel();
        txt_buscarusuario = new javax.swing.JLabel();
        txt_buscarc = new javax.swing.JTextField();
        buscarCBtn = new javax.swing.JPanel();
        txt_buscarcedula = new javax.swing.JLabel();
        txt_buscarUser = new javax.swing.JTextField();
        paneltabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_usuarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        actualizarBtnUsuario = new javax.swing.JPanel();
        txt_Actualiz = new javax.swing.JLabel();
        actualizarTablaBtn = new javax.swing.JPanel();
        txt_actualizartblaBtn = new javax.swing.JLabel();
        ContenAct = new javax.swing.JPanel();
        addUserBtn = new javax.swing.JPanel();
        txt_addUser = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarUsuarioBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_buscarusuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_buscarusuario.setText("   Buscar Usuario:");
        txt_buscarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_buscarusuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarUsuarioBtnLayout = new javax.swing.GroupLayout(buscarUsuarioBtn);
        buscarUsuarioBtn.setLayout(buscarUsuarioBtnLayout);
        buscarUsuarioBtnLayout.setHorizontalGroup(
            buscarUsuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        buscarUsuarioBtnLayout.setVerticalGroup(
            buscarUsuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(buscarUsuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        txt_buscarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarcActionPerformed(evt);
            }
        });
        jPanel1.add(txt_buscarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        buscarCBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_buscarcedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_buscarcedula.setText("   Buscar cedula:");
        txt_buscarcedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarcedulaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_buscarcedulaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_buscarcedulaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarCBtnLayout = new javax.swing.GroupLayout(buscarCBtn);
        buscarCBtn.setLayout(buscarCBtnLayout);
        buscarCBtnLayout.setHorizontalGroup(
            buscarCBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarcedula, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        buscarCBtnLayout.setVerticalGroup(
            buscarCBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscarcedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(buscarCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        txt_buscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarUserActionPerformed(evt);
            }
        });
        jPanel1.add(txt_buscarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 30));

        paneltabla.setBackground(new java.awt.Color(153, 153, 153));
        paneltabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_usuarios);

        paneltabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 190));

        jPanel1.add(paneltabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 710, 190));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                    GESTION DE USUARIOS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 480, 40));

        actualizarBtnUsuario.setBackground(new java.awt.Color(255, 255, 255));

        txt_Actualiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_Actualiz.setText("     Actualizar usuarios");
        txt_Actualiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ActualizMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ActualizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ActualizMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarBtnUsuarioLayout = new javax.swing.GroupLayout(actualizarBtnUsuario);
        actualizarBtnUsuario.setLayout(actualizarBtnUsuarioLayout);
        actualizarBtnUsuarioLayout.setHorizontalGroup(
            actualizarBtnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Actualiz, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        actualizarBtnUsuarioLayout.setVerticalGroup(
            actualizarBtnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Actualiz, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(actualizarBtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 140, 30));

        actualizarTablaBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_actualizartblaBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_actualizartblaBtn.setText("        Actualizar tabla");
        txt_actualizartblaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_actualizartblaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_actualizartblaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_actualizartblaBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout actualizarTablaBtnLayout = new javax.swing.GroupLayout(actualizarTablaBtn);
        actualizarTablaBtn.setLayout(actualizarTablaBtnLayout);
        actualizarTablaBtnLayout.setHorizontalGroup(
            actualizarTablaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizartblaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        actualizarTablaBtnLayout.setVerticalGroup(
            actualizarTablaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_actualizartblaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(actualizarTablaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 140, 30));

        ContenAct.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout ContenActLayout = new javax.swing.GroupLayout(ContenAct);
        ContenAct.setLayout(ContenActLayout);
        ContenActLayout.setHorizontalGroup(
            ContenActLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ContenActLayout.setVerticalGroup(
            ContenActLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.add(ContenAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 600, 180));

        addUserBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_addUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_addUser.setText("      Agregar Usuario");
        txt_addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_addUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_addUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout addUserBtnLayout = new javax.swing.GroupLayout(addUserBtn);
        addUserBtn.setLayout(addUserBtnLayout);
        addUserBtnLayout.setHorizontalGroup(
            addUserBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_addUser, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        addUserBtnLayout.setVerticalGroup(
            addUserBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_addUser, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarcActionPerformed

    private void txt_buscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarUserActionPerformed

    private void txt_buscarusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseEntered
        buscarUsuarioBtn.setBackground(new Color(0, 153, 255));
        txt_buscarusuario.setForeground(Color.white);
    }//GEN-LAST:event_txt_buscarusuarioMouseEntered

    private void txt_buscarusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseExited
        buscarUsuarioBtn.setBackground(Color.white);
        txt_buscarusuario.setForeground(Color.black);
    }//GEN-LAST:event_txt_buscarusuarioMouseExited

    private void txt_buscarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarusuarioMouseClicked
        user.buscarUsuarioPorUser(GetTxtbuscaruser());
        txt_buscarUser.setText("");
    }//GEN-LAST:event_txt_buscarusuarioMouseClicked

    private void txt_buscarcedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcedulaMouseClicked
        user.buscarUsuarioPorCedula(GetTxtbuscarC());
        txt_buscarc.setText("");
    }//GEN-LAST:event_txt_buscarcedulaMouseClicked

    private void txt_actualizartblaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizartblaBtnMouseClicked
        CargarTablaUsuario();
    }//GEN-LAST:event_txt_actualizartblaBtnMouseClicked

    private void txt_ActualizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ActualizMouseClicked
        
        ShowPanel(act);
    }//GEN-LAST:event_txt_ActualizMouseClicked

    private void txt_buscarcedulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcedulaMouseEntered
        buscarCBtn.setBackground(new Color(0, 153, 255));
        txt_buscarcedula.setForeground(Color.white);
    }//GEN-LAST:event_txt_buscarcedulaMouseEntered

    private void txt_ActualizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ActualizMouseEntered
        actualizarBtnUsuario.setBackground(new Color(0, 153, 255));
        txt_Actualiz.setForeground(Color.white);
    }//GEN-LAST:event_txt_ActualizMouseEntered

    private void txt_actualizartblaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizartblaBtnMouseEntered
        actualizarTablaBtn.setBackground(new Color(0, 153, 255));
        actualizarTablaBtn.setForeground(Color.white);
    }//GEN-LAST:event_txt_actualizartblaBtnMouseEntered

    private void txt_buscarcedulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcedulaMouseExited
         buscarCBtn.setBackground(Color.white);
        txt_buscarcedula.setForeground(Color.black);
    }//GEN-LAST:event_txt_buscarcedulaMouseExited

    private void txt_ActualizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ActualizMouseExited
        actualizarBtnUsuario.setBackground(Color.white);
        txt_Actualiz.setForeground(Color.black);
    }//GEN-LAST:event_txt_ActualizMouseExited

    private void txt_actualizartblaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_actualizartblaBtnMouseExited
        actualizarTablaBtn.setBackground(Color.white);
        txt_actualizartblaBtn.setForeground(Color.black);
    }//GEN-LAST:event_txt_actualizartblaBtnMouseExited

    private void txt_addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addUserMouseClicked
        ShowPanel(addUser);
    }//GEN-LAST:event_txt_addUserMouseClicked

    private void txt_addUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addUserMouseEntered
        addUserBtn.setBackground(new Color(0, 153, 255));
        txt_addUser.setForeground(Color.white);
    }//GEN-LAST:event_txt_addUserMouseEntered

    private void txt_addUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addUserMouseExited
        addUserBtn.setBackground(Color.white);
        txt_addUser.setForeground(Color.black);
    }//GEN-LAST:event_txt_addUserMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenAct;
    private javax.swing.JPanel actualizarBtnUsuario;
    private javax.swing.JPanel actualizarTablaBtn;
    private javax.swing.JPanel addUserBtn;
    private javax.swing.JPanel buscarCBtn;
    private javax.swing.JPanel buscarUsuarioBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_usuarios;
    private javax.swing.JPanel paneltabla;
    private javax.swing.JLabel txt_Actualiz;
    private javax.swing.JLabel txt_actualizartblaBtn;
    private javax.swing.JLabel txt_addUser;
    private javax.swing.JTextField txt_buscarUser;
    private javax.swing.JTextField txt_buscarc;
    private javax.swing.JLabel txt_buscarcedula;
    private javax.swing.JLabel txt_buscarusuario;
    // End of variables declaration//GEN-END:variables

    public String GetTxtbuscaruser() {
        return txt_buscarUser.getText();
    }

    public String GetTxtbuscarC() {
        return txt_buscarc.getText();
    }

    private void ShowPanel(JPanel p) {
        p.setSize(600, 180);
        p.setLocation(0, 0);
        ContenAct.removeAll();
        ContenAct.setLayout(new BorderLayout());
        ContenAct.add(p, BorderLayout.CENTER);
        ContenAct.revalidate();
        ContenAct.repaint();

    }

//Cargar la tabla de usuarios registrados
    public void CargarTablaUsuario() {
        Connection con = Conexionmy.Conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT id_usuario, nombre_usuario, rol, cedula, userlogin FROM usuarios;";
        Statement st;

        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            model.addColumn("N°");
            model.addColumn("nombre");
            //model.addColumn("clave");
            model.addColumn("rol");
            model.addColumn("cedula");
            model.addColumn("User");

            while (rs.next()) {

                Object fila[] = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);

                }

                model.addRow(fila);
            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar tabla usuario" + e);
        }
        jTable_usuarios.setModel(model);
        

        jTable_usuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_usuarios.rowAtPoint(e.getPoint());
                int columna_point = 0;
                int selectedRow = jTable_usuarios.getSelectedRow();

                if (fila_point >= 0) {
                    id_cliente = (int) jTable_usuarios.getValueAt(selectedRow, 0);
                    act.PasaridUsuario(id_cliente);
                    act.EnviarDatosClienteSeleccionada(id_cliente);
                    
                    //EnviarDatosClienteSeleccionada(idCliente);

                }
            }
        });
    }

}
