/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Controladores.ControladorCliente;
import Controladores.ControladorUsuario;
import Modelos.Usuario;
import Modelos.ValidarSesion;

import com.mysql.jdbc.interceptors.SessionAssociationInterceptor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Panel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Bryan
 */
public class Vista_Menu_Prueba extends javax.swing.JFrame {

    int xmouse, ymouse;

    public static JDesktopPane jDesktopPane_menu;
    String rutaimglogo = "/img/logoC.png";
    String rutalogopantalla = "/img/logoC.png";
//    GestionClientes.jDesktopPane_men= this.jDesktopPane_men;

//    private JMenuItem menucliente;
//    private JMenuItem menucreditos;
//    private JMenuItem menuusuario;
//    private JMenuItem menutransacciones;
//    private JMenuItem menusalir;
//
//    private String icon_clientes = "/img/clasificacion.png";
//    private String icon_creditos = "/img/tarjetas-de-credito.png";
//    private String icon_usuario = "/img/agregarusuario.png";
//    private String icon_transacciones = "/img/transaccion.png";
//    private String icon_salir = "/img/cerrarsesion.png";
    /**
     * Creates new form Vista_Menu
     */
    public Vista_Menu_Prueba() {
        initComponents();

        ajustarImagenAlLabel(jLabel2, rutaimglogo);
        //ajustarImagenAlLabel(jLabel1, rutalogopantalla);
        jDesktopPane_menu = new JDesktopPane();
        //ControladorUsuario user = new ControladorUsuario();
        add(jDesktopPane_menu, BorderLayout.CENTER); // o setContentPane(jDesktopPane_menu);
        //this.setSize(new Dimension(905, 542));

//        menucliente = new JMenuItem("CLIENTES", getIcono(icon_clientes));
//        menucreditos = new JMenuItem("CREDITOS", getIcono(icon_creditos));
//        menuusuario = new JMenuItem("USUARIO", getIcono(icon_usuario));
//        menutransacciones = new JMenuItem("TRANSACCIÓN", getIcono(icon_transacciones));
//        menusalir = new JMenuItem("SALIR", getIcono(icon_salir));
//        jMenuBar.add(menuusuario);
//        jMenuBar.add(menucliente);
//        jMenuBar.add(menucreditos);
//        jMenuBar.add(menutransacciones);
//        jMenuBar.add(menusalir);
        //jDesktopPane_menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);

        //abrir ventana de gestionar clientes
//        menucliente.addActionListener((e) -> {
//            GestionClientes gerstionclientes = new GestionClientes();
//            jDesktopPane_menu.add(gerstionclientes);
//            gerstionclientes.setVisible(true);
//        });
        //abrir ventana de gestionar usuarios
//        menuusuario.addActionListener((e) -> {
//            GestionUsuarios gerstionUsuario = new GestionUsuarios();
//
//            try {
//
//                if (Usuario.getRolSession().equals("admin")) {
//                    jDesktopPane_menu.add(gerstionUsuario);
//                    gerstionUsuario.setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(null, "No tienes permisos para acceder.");
//                }
//            } catch (Exception ex) {
//                System.out.println("Error al ejecutar" + ex);
//                JOptionPane.showMessageDialog(null, "ocurrio un error consulte con del Dev.");
//            }
//        });
    }

    private Icon getIcono(String ruta) {
        return new ImageIcon(new ImageIcon(getClass().getResource(ruta))
                .getImage().getScaledInstance(30, 30, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        x_SalirBtn = new javax.swing.JPanel();
        txt_XSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuarioBtn = new javax.swing.JPanel();
        txt_usuario = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        creditosBtn = new javax.swing.JPanel();
        txt_creditos = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        transaccionBtn = new javax.swing.JPanel();
        txt_transaccion = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        histPagosBtn = new javax.swing.JPanel();
        txt_HistPagos = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        salirBtn1 = new javax.swing.JPanel();
        txt_salir1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        clienteBtn = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(106, 207, 241));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x_SalirBtn.setBackground(new java.awt.Color(106, 207, 241));
        x_SalirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_XSalir.setBackground(new java.awt.Color(106, 207, 241));
        txt_XSalir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txt_XSalir.setForeground(new java.awt.Color(255, 255, 255));
        txt_XSalir.setText("   X");
        txt_XSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_XSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_XSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_XSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout x_SalirBtnLayout = new javax.swing.GroupLayout(x_SalirBtn);
        x_SalirBtn.setLayout(x_SalirBtnLayout);
        x_SalirBtnLayout.setHorizontalGroup(
            x_SalirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_XSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );
        x_SalirBtnLayout.setVerticalGroup(
            x_SalirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_XSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel8.add(x_SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoC.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 117));
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        content.setBackground(new java.awt.Color(106, 207, 241));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo pro.png"))); // NOI18N
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 340, 140));

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1010, 570));

        usuarioBtn.setBackground(new java.awt.Color(255, 255, 255));
        usuarioBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_usuario.setText("   USUARIOS");
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseExited(evt);
            }
        });
        usuarioBtn.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 130, 40));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        usuarioBtn.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 40));

        jPanel1.add(usuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        creditosBtn.setBackground(new java.awt.Color(255, 255, 255));
        creditosBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_creditos.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_creditos.setText("       CREDITOS");
        txt_creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_creditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_creditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_creditosMouseExited(evt);
            }
        });
        creditosBtn.add(txt_creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 8, 110, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        creditosBtn.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 40));

        jPanel1.add(creditosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 160, -1));

        transaccionBtn.setBackground(new java.awt.Color(255, 255, 255));
        transaccionBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_transaccion.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_transaccion.setText(" CLIENTES EN RIESGO");
        txt_transaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_transaccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_transaccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_transaccionMouseExited(evt);
            }
        });
        transaccionBtn.add(txt_transaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 40));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        transaccionBtn.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 40));

        jPanel1.add(transaccionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 190, -1));

        histPagosBtn.setBackground(new java.awt.Color(255, 255, 255));
        histPagosBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_HistPagos.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_HistPagos.setText("   HISTORIAL DE PAGOS");
        txt_HistPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_HistPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_HistPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_HistPagosMouseExited(evt);
            }
        });
        histPagosBtn.add(txt_HistPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        histPagosBtn.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 40));

        jPanel1.add(histPagosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 210, -1));

        salirBtn1.setBackground(new java.awt.Color(255, 255, 255));
        salirBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirBtn1MouseExited(evt);
            }
        });

        txt_salir1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_salir1.setText("      SALIR");
        txt_salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_salir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_salir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_salir1MouseExited(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setAlignmentX(1.0F);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout salirBtn1Layout = new javax.swing.GroupLayout(salirBtn1);
        salirBtn1.setLayout(salirBtn1Layout);
        salirBtn1Layout.setHorizontalGroup(
            salirBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salirBtn1Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        salirBtn1Layout.setVerticalGroup(
            salirBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_salir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(salirBtn1Layout.createSequentialGroup()
                .addGroup(salirBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(salirBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 140, -1));

        clienteBtn.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txt_cliente.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_cliente.setText("   CLIENTES");
        txt_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_clienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout clienteBtnLayout = new javax.swing.GroupLayout(clienteBtn);
        clienteBtn.setLayout(clienteBtnLayout);
        clienteBtnLayout.setHorizontalGroup(
            clienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteBtnLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        clienteBtnLayout.setVerticalGroup(
            clienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteBtnLayout.createSequentialGroup()
                .addGroup(clienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(clienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        int x = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(x - xmouse, Y - ymouse);
    }//GEN-LAST:event_jPanel8MouseDragged

    private void txt_XSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XSalirMouseEntered
        x_SalirBtn.setBackground(Color.red);
        txt_XSalir.setForeground(Color.black);
    }//GEN-LAST:event_txt_XSalirMouseEntered

    private void txt_XSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XSalirMouseExited
        x_SalirBtn.setBackground(new Color(0, 153, 204));
        txt_XSalir.setForeground(Color.white);
    }//GEN-LAST:event_txt_XSalirMouseExited

    private void txt_XSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txt_XSalirMouseClicked

    private void txt_salir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salir1MouseExited
        salirBtn1.setBackground(Color.white);
        txt_salir1.setForeground(Color.black);
    }//GEN-LAST:event_txt_salir1MouseExited

    private void txt_salir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salir1MouseEntered
        salirBtn1.setBackground(new Color(0, 153, 255));
        txt_salir1.setForeground(Color.white);
    }//GEN-LAST:event_txt_salir1MouseEntered

    private void txt_salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_txt_salir1MouseClicked

    private void txt_HistPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HistPagosMouseExited
        histPagosBtn.setBackground(Color.white);
        txt_HistPagos.setForeground(Color.black);
    }//GEN-LAST:event_txt_HistPagosMouseExited

    private void txt_HistPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HistPagosMouseEntered
        histPagosBtn.setBackground(new Color(0, 153, 255));
        txt_HistPagos.setForeground(Color.white);
    }//GEN-LAST:event_txt_HistPagosMouseEntered

    private void txt_HistPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HistPagosMouseClicked
        HistorialDePagos historial = new HistorialDePagos();
        ValidadInicioDeSesion("Historial",historial);


    }//GEN-LAST:event_txt_HistPagosMouseClicked

    private void txt_transaccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transaccionMouseExited
        transaccionBtn.setBackground(Color.white);
        txt_transaccion.setForeground(Color.black);
    }//GEN-LAST:event_txt_transaccionMouseExited

    private void txt_transaccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transaccionMouseEntered
        transaccionBtn.setBackground(new Color(0, 153, 255));
        txt_transaccion.setForeground(Color.white);
    }//GEN-LAST:event_txt_transaccionMouseEntered

    private void txt_transaccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transaccionMouseClicked
        TblaClientesAtrasados atrasados = new TblaClientesAtrasados();
        ValidadInicioDeSesion("Atrasados",atrasados);


    }//GEN-LAST:event_txt_transaccionMouseClicked

    private void txt_creditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_creditosMouseExited
        creditosBtn.setBackground(Color.white);
        txt_creditos.setForeground(Color.black);
    }//GEN-LAST:event_txt_creditosMouseExited

    private void txt_creditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_creditosMouseEntered
        creditosBtn.setBackground(new Color(0, 153, 255));
        txt_creditos.setForeground(Color.white);
    }//GEN-LAST:event_txt_creditosMouseEntered

    private void txt_creditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_creditosMouseClicked
        CreditosG cred = new CreditosG();

        ValidadInicioDeSesion("Creditos",cred);


    }//GEN-LAST:event_txt_creditosMouseClicked

    private void txt_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_clienteMouseExited
        clienteBtn.setBackground(Color.white);
        txt_cliente.setForeground(Color.black);
    }//GEN-LAST:event_txt_clienteMouseExited

    private void txt_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_clienteMouseEntered
        clienteBtn.setBackground(new Color(0, 153, 255));
        txt_cliente.setForeground(Color.white);
    }//GEN-LAST:event_txt_clienteMouseEntered

    private void txt_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_clienteMouseClicked
        ClientesG client = new ClientesG();
        ValidadInicioDeSesion("Clientes",client);


    }//GEN-LAST:event_txt_clienteMouseClicked

    private void txt_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseExited
        usuarioBtn.setBackground(Color.white);
        txt_usuario.setForeground(Color.black);
    }//GEN-LAST:event_txt_usuarioMouseExited

    private void txt_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseEntered
        usuarioBtn.setBackground(new Color(0, 153, 255));
        txt_usuario.setForeground(Color.white);
    }//GEN-LAST:event_txt_usuarioMouseEntered

    private void txt_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseClicked

        UsuarioG user = new UsuarioG();

        ValidadInicioDeSesion("Usuarios",user);

        

    }//GEN-LAST:event_txt_usuarioMouseClicked

    private void salirBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtn1MouseEntered
        salirBtn1.setBackground(new Color(0, 153, 255));
        txt_salir1.setForeground(Color.white);
    }//GEN-LAST:event_salirBtn1MouseEntered

    private void salirBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtn1MouseExited
        salirBtn1.setBackground(Color.white);
        txt_salir1.setForeground(Color.black);
    }//GEN-LAST:event_salirBtn1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Menu_Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clienteBtn;
    private javax.swing.JPanel content;
    private javax.swing.JPanel creditosBtn;
    private javax.swing.JPanel histPagosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel salirBtn1;
    private javax.swing.JPanel transaccionBtn;
    private javax.swing.JLabel txt_HistPagos;
    private javax.swing.JLabel txt_XSalir;
    private javax.swing.JLabel txt_cliente;
    private javax.swing.JLabel txt_creditos;
    private javax.swing.JLabel txt_salir1;
    private javax.swing.JLabel txt_transaccion;
    private javax.swing.JLabel txt_usuario;
    private javax.swing.JPanel usuarioBtn;
    private javax.swing.JPanel x_SalirBtn;
    // End of variables declaration//GEN-END:variables

    private void ShowPanel(JPanel p) {
        p.setSize(690, 590);
        p.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    private void ajustarImagenAlLabel(JLabel label, String ruta) {
        // Cargar la imagen desde el archivo
        ImageIcon imagenOriginal = new ImageIcon(getClass().getResource(ruta));

        // Redimensionar la imagen al tamaño del JLabel
        Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );

        // Crear nuevo icono redimensionado
        ImageIcon iconoRedimensionado = new ImageIcon(imagenEscalada);

        // Asignar la imagen redimensionada al JLabel
        label.setIcon(iconoRedimensionado);
    }

    public void ValidadInicioDeSesion(String tipoDeVentana, JPanel panel) {

        if (tipoDeVentana.equals("Usuarios")) {
            try {
            if (ValidarSesion.getRolsesion().equals("admin")) {
                ShowPanel(panel);
            } else {
                JOptionPane.showMessageDialog(null, "No tiene Acceso");
            }
            } catch (Exception ex) {
                //System.out.println("Ocurrio un error" + ex);
                JOptionPane.showMessageDialog(null, "No mantiene permiso de administrador.");
            }
            
        } else {
            try {

                if (ValidarSesion.getRolsesion().equals("admin") || !ValidarSesion.getRolsesion().isEmpty()) {
                    ShowPanel(panel);

                } else {
                    JOptionPane.showMessageDialog(null, "No tiene Acceso");
                }
            } catch (Exception ex) {
                System.out.println("Ocurrio un error" + ex);
                JOptionPane.showMessageDialog(null, "debe iniciar sesion para continuar.");
            }

        }

    }

}
