/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Controladores.ControladorCliente;
import Controladores.ControladorUsuario;
import Modelos.Usuario;

import com.mysql.jdbc.interceptors.SessionAssociationInterceptor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Panel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Bryan
 */
public class Vista_Menu_Prueba extends javax.swing.JFrame {

    int xmouse, ymouse;

    public static JDesktopPane jDesktopPane_menu;
//    GestionClientes.jDesktopPane_men= this.jDesktopPane_men;

//    private JMenuItem menucliente;
//    private JMenuItem menucreditos;
//    private JMenuItem menuusuario;
//    private JMenuItem menutransacciones;
//    private JMenuItem menusalir;
//
//    private String icon_clientes = "/img/clasificacion.png";
//    private String icon_creditos = "/img/tarjetas-de-credito.png";
//    private String icon_usuario = "/img/agregarusuario.png";
//    private String icon_transacciones = "/img/transaccion.png";
//    private String icon_salir = "/img/cerrarsesion.png";
    /**
     * Creates new form Vista_Menu
     */
    public Vista_Menu_Prueba() {
        initComponents();

        jDesktopPane_menu = new JDesktopPane();
        //ControladorUsuario user = new ControladorUsuario();
        add(jDesktopPane_menu, BorderLayout.CENTER); // o setContentPane(jDesktopPane_menu);
        //this.setSize(new Dimension(905, 542));

//        menucliente = new JMenuItem("CLIENTES", getIcono(icon_clientes));
//        menucreditos = new JMenuItem("CREDITOS", getIcono(icon_creditos));
//        menuusuario = new JMenuItem("USUARIO", getIcono(icon_usuario));
//        menutransacciones = new JMenuItem("TRANSACCIÓN", getIcono(icon_transacciones));
//        menusalir = new JMenuItem("SALIR", getIcono(icon_salir));
//        jMenuBar.add(menuusuario);
//        jMenuBar.add(menucliente);
//        jMenuBar.add(menucreditos);
//        jMenuBar.add(menutransacciones);
//        jMenuBar.add(menusalir);
        //jDesktopPane_menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);

        //abrir ventana de gestionar clientes
//        menucliente.addActionListener((e) -> {
//            GestionClientes gerstionclientes = new GestionClientes();
//            jDesktopPane_menu.add(gerstionclientes);
//            gerstionclientes.setVisible(true);
//        });
        //abrir ventana de gestionar usuarios
//        menuusuario.addActionListener((e) -> {
//            GestionUsuarios gerstionUsuario = new GestionUsuarios();
//
//            try {
//
//                if (Usuario.getRolSession().equals("admin")) {
//                    jDesktopPane_menu.add(gerstionUsuario);
//                    gerstionUsuario.setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(null, "No tienes permisos para acceder.");
//                }
//            } catch (Exception ex) {
//                System.out.println("Error al ejecutar" + ex);
//                JOptionPane.showMessageDialog(null, "ocurrio un error consulte con del Dev.");
//            }
//        });
    }

    
    private Icon getIcono(String ruta) {
        return new ImageIcon(new ImageIcon(getClass().getResource(ruta))
                .getImage().getScaledInstance(30, 30, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        x_SalirBtn = new javax.swing.JPanel();
        txt_XSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        usuarioBtn = new javax.swing.JPanel();
        txt_usuario = new javax.swing.JLabel();
        clienteBtn = new javax.swing.JPanel();
        txt_cliente = new javax.swing.JLabel();
        creditosBtn = new javax.swing.JPanel();
        txt_creditos = new javax.swing.JLabel();
        transaccionBtn = new javax.swing.JPanel();
        txt_transaccion = new javax.swing.JLabel();
        salirBtn = new javax.swing.JPanel();
        txt_salir = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 153, 204));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x_SalirBtn.setBackground(new java.awt.Color(0, 153, 204));
        x_SalirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_XSalir.setBackground(new java.awt.Color(0, 153, 153));
        txt_XSalir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txt_XSalir.setForeground(new java.awt.Color(255, 255, 255));
        txt_XSalir.setText("   X");
        txt_XSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_XSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_XSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_XSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout x_SalirBtnLayout = new javax.swing.GroupLayout(x_SalirBtn);
        x_SalirBtn.setLayout(x_SalirBtnLayout);
        x_SalirBtnLayout.setHorizontalGroup(
            x_SalirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_XSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );
        x_SalirBtnLayout.setVerticalGroup(
            x_SalirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_XSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel8.add(x_SalirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 50));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  CREDITOS Y PRESTAMOS");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 10));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 598));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_usuario.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_usuario.setText("                    USUARIOS");
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout usuarioBtnLayout = new javax.swing.GroupLayout(usuarioBtn);
        usuarioBtn.setLayout(usuarioBtnLayout);
        usuarioBtnLayout.setHorizontalGroup(
            usuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        usuarioBtnLayout.setVerticalGroup(
            usuarioBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(usuarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 40));

        clienteBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_cliente.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_cliente.setText("                  CLIENTES");
        txt_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_clienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout clienteBtnLayout = new javax.swing.GroupLayout(clienteBtn);
        clienteBtn.setLayout(clienteBtnLayout);
        clienteBtnLayout.setHorizontalGroup(
            clienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteBtnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txt_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        clienteBtnLayout.setVerticalGroup(
            clienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteBtnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txt_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel2.add(clienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 40));

        creditosBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_creditos.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_creditos.setText("                  CREDITOS");
        txt_creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_creditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_creditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_creditosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout creditosBtnLayout = new javax.swing.GroupLayout(creditosBtn);
        creditosBtn.setLayout(creditosBtnLayout);
        creditosBtnLayout.setHorizontalGroup(
            creditosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditosBtnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txt_creditos, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        creditosBtnLayout.setVerticalGroup(
            creditosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditosBtnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txt_creditos, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel2.add(creditosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 40));

        transaccionBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_transaccion.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_transaccion.setText("                 TRANSACCIÓN");
        txt_transaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_transaccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_transaccionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout transaccionBtnLayout = new javax.swing.GroupLayout(transaccionBtn);
        transaccionBtn.setLayout(transaccionBtnLayout);
        transaccionBtnLayout.setHorizontalGroup(
            transaccionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_transaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        transaccionBtnLayout.setVerticalGroup(
            transaccionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_transaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(transaccionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 40));

        salirBtn.setBackground(new java.awt.Color(255, 255, 255));

        txt_salir.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_salir.setText("                       SALIR");
        txt_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 240, -1));

        content.setBackground(new java.awt.Color(153, 153, 153));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 770, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        int x = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(x - xmouse, Y - ymouse);
    }//GEN-LAST:event_jPanel8MouseDragged

    private void txt_XSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XSalirMouseEntered
        x_SalirBtn.setBackground(Color.red);
        txt_XSalir.setForeground(Color.black);
    }//GEN-LAST:event_txt_XSalirMouseEntered

    private void txt_XSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XSalirMouseExited
        x_SalirBtn.setBackground(new Color(0,153,204));
        txt_XSalir.setForeground(Color.white);
    }//GEN-LAST:event_txt_XSalirMouseExited

    private void txt_XSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_XSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txt_XSalirMouseClicked

    private void txt_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseEntered
        usuarioBtn.setBackground(new Color(0, 153, 255));
        txt_usuario.setForeground(Color.white);
    }//GEN-LAST:event_txt_usuarioMouseEntered

    private void txt_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseExited
        usuarioBtn.setBackground(Color.white);
        txt_usuario.setForeground(Color.black);
    }//GEN-LAST:event_txt_usuarioMouseExited

    private void txt_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_clienteMouseEntered
        clienteBtn.setBackground(new Color(0, 153, 255));
        txt_cliente.setForeground(Color.white);
    }//GEN-LAST:event_txt_clienteMouseEntered

    private void txt_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_clienteMouseExited
        clienteBtn.setBackground(Color.white);
        txt_cliente.setForeground(Color.black);
    }//GEN-LAST:event_txt_clienteMouseExited

    private void txt_creditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_creditosMouseEntered
        creditosBtn.setBackground(new Color(0, 153, 255));
        txt_creditos.setForeground(Color.white);
    }//GEN-LAST:event_txt_creditosMouseEntered

    private void txt_creditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_creditosMouseExited
        creditosBtn.setBackground(Color.white);
        txt_creditos.setForeground(Color.black);
    }//GEN-LAST:event_txt_creditosMouseExited

    private void txt_transaccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transaccionMouseEntered
        transaccionBtn.setBackground(new Color(0, 153, 255));
        txt_transaccion.setForeground(Color.white);
    }//GEN-LAST:event_txt_transaccionMouseEntered

    private void txt_transaccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_transaccionMouseExited
        transaccionBtn.setBackground(Color.white);
        txt_transaccion.setForeground(Color.black);
    }//GEN-LAST:event_txt_transaccionMouseExited

    private void txt_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salirMouseEntered
        salirBtn.setBackground(new Color(0, 153, 255));
        txt_salir.setForeground(Color.white);
    }//GEN-LAST:event_txt_salirMouseEntered

    private void txt_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_salirMouseExited
        salirBtn.setBackground(Color.white);
        txt_salir.setForeground(Color.black);
    }//GEN-LAST:event_txt_salirMouseExited

    private void txt_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseClicked
        
        
        UsuarioG user = new UsuarioG();
        try{
            if(Usuario.getRolSession().equals("admin")){
                ShowPanel(user);
            }else{
                JOptionPane.showMessageDialog(null, "No tiene Acceso");
            }
        }catch(Exception ex)
            {
                System.out.println("Ocurrio un error" + ex);
                JOptionPane.showMessageDialog(null, "Ocurrio un error, contactese con su proveedor");
            }


    }//GEN-LAST:event_txt_usuarioMouseClicked

    private void txt_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_clienteMouseClicked
        ClientesG client = new ClientesG();
        ShowPanel(client);
    }//GEN-LAST:event_txt_clienteMouseClicked

    private void txt_creditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_creditosMouseClicked
        CreditosG cred = new CreditosG();
        ShowPanel(cred);
    }//GEN-LAST:event_txt_creditosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu_Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Menu_Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clienteBtn;
    private javax.swing.JPanel content;
    private javax.swing.JPanel creditosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JPanel transaccionBtn;
    private javax.swing.JLabel txt_XSalir;
    private javax.swing.JLabel txt_cliente;
    private javax.swing.JLabel txt_creditos;
    private javax.swing.JLabel txt_salir;
    private javax.swing.JLabel txt_transaccion;
    private javax.swing.JLabel txt_usuario;
    private javax.swing.JPanel usuarioBtn;
    private javax.swing.JPanel x_SalirBtn;
    // End of variables declaration//GEN-END:variables

private void ShowPanel(JPanel p) {
        p.setSize(690, 590);
        p.setLocation(0, 0);
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }





}
